/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package OrganizedIn.UI;

import OrganizedIn.Audit.AuditItem;
import OrganizedIn.Data.AuditDAO;
import OrganizedIn.Data.AuditItemDAO;
import OrganizedIn.Lib.Audit;
import OrganizedIn.Lib.ReportViewer;
import OrganizedIn.UI.Lib.AuditUpdate;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author gamunu
 */
public class AuditPanel extends javax.swing.JPanel {

    private Vector<Vector<String>> AuditList2;
    private Vector<Vector<String>> AuditList;
    private Vector<String> AuditHeader;
    private Vector<String> AuditHeader2;

    /**
     * Creates new form AuditPanel
     */
    public AuditPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane16 = new javax.swing.JTabbedPane();
        jPanel52 = new javax.swing.JPanel();
        jTabbedPane17 = new javax.swing.JTabbedPane();
        jPanel53 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane22 = new javax.swing.JScrollPane();
        audNotes = new javax.swing.JTextPane();
        jLabel33 = new javax.swing.JLabel();
        jButton67 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        AudNo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        auditorNames = new javax.swing.JTextArea();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        stDate = new com.toedter.calendar.JDateChooser();
        jPanel54 = new javax.swing.JPanel();
        jScrollPane23 = new javax.swing.JScrollPane();
        searchAuditResults = new javax.swing.JTable();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        AudSearch = new javax.swing.JTextField();
        jPanel55 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jTextField91 = new javax.swing.JTextField();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jLabel126 = new javax.swing.JLabel();
        jLabel127 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        jTextField92 = new javax.swing.JTextField();
        jTextField93 = new javax.swing.JTextField();
        jTextField94 = new javax.swing.JTextField();
        jLabel129 = new javax.swing.JLabel();
        jScrollPane24 = new javax.swing.JScrollPane();
        jTable17 = new javax.swing.JTable();
        jLabel130 = new javax.swing.JLabel();
        jComboBox11 = new javax.swing.JComboBox();
        jLabel131 = new javax.swing.JLabel();
        jComboBox12 = new javax.swing.JComboBox();
        audNum = new javax.swing.JComboBox();
        jPanel57 = new javax.swing.JPanel();
        jButton75 = new javax.swing.JButton();
        jButton76 = new javax.swing.JButton();
        jPanel49 = new javax.swing.JPanel();
        jScrollPane18 = new javax.swing.JScrollPane();
        searchAuditResults2 = new javax.swing.JTable();
        Damage = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel132 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        jTabbedPane16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTabbedPane16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane16MouseClicked(evt);
            }
        });

        jTabbedPane17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("From Date");

        audNotes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane22.setViewportView(audNotes);

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel33.setText("Auditors");

        jButton67.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Save.png"))); // NOI18N
        jButton67.setText("Add");
        jButton67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton67ActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel36.setText("To Date");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Audit No");

        AudNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AudNoActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Note");

        auditorNames.setColumns(20);
        auditorNames.setRows(5);
        jScrollPane1.setViewportView(auditorNames);

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jDateChooser1.setMaxSelectableDate(new java.util.Date(253370748681000L));
        jDateChooser1.setMinSelectableDate(new java.util.Date(-62135785719000L));

        stDate.setDateFormatString("yyyy-MM-dd");

        org.jdesktop.layout.GroupLayout jPanel53Layout = new org.jdesktop.layout.GroupLayout(jPanel53);
        jPanel53.setLayout(jPanel53Layout);
        jPanel53Layout.setHorizontalGroup(
            jPanel53Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel53Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel53Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel53Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jPanel53Layout.createSequentialGroup()
                            .add(jLabel1)
                            .add(28, 28, 28)
                            .add(AudNo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 250, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(jPanel53Layout.createSequentialGroup()
                            .add(jPanel53Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(jLabel12)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel19)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 71, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(jLabel33))
                            .add(jPanel53Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(jPanel53Layout.createSequentialGroup()
                                    .add(18, 18, 18)
                                    .add(jPanel53Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 250, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(jScrollPane22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 250, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                .add(jPanel53Layout.createSequentialGroup()
                                    .add(18, 18, 18)
                                    .add(jPanel53Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                        .add(jDateChooser1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(stDate, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))))))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jButton67))
                .add(443, 443, 443))
        );
        jPanel53Layout.setVerticalGroup(
            jPanel53Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel53Layout.createSequentialGroup()
                .add(32, 32, 32)
                .add(jPanel53Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(AudNo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .add(18, 18, 18)
                .add(jPanel53Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel12)
                    .add(jDateChooser1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(10, 10, 10)
                .add(jPanel53Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel36)
                    .add(stDate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel53Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel33))
                .add(18, 18, 18)
                .add(jPanel53Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel19)
                    .add(jScrollPane22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 86, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(32, 32, 32)
                .add(jButton67)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jTabbedPane17.addTab("Add New Audit", jPanel53);

        searchAuditResults.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchAuditResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Audit ID", "Start Date", "End Date", "Auditors", "Note"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane23.setViewportView(searchAuditResults);

        jButton68.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Update.png"))); // NOI18N
        jButton68.setText("Update");
        jButton68.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton68ActionPerformed(evt);
            }
        });

        jButton69.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Recycle Bin Full.png"))); // NOI18N
        jButton69.setText("Delete");
        jButton69.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton69ActionPerformed(evt);
            }
        });

        jLabel2.setText("Audit ID ");

        AudSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AudSearchKeyReleased(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel54Layout = new org.jdesktop.layout.GroupLayout(jPanel54);
        jPanel54.setLayout(jPanel54Layout);
        jPanel54Layout.setHorizontalGroup(
            jPanel54Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel54Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel54Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane23, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 843, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel54Layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(jButton68)
                        .add(28, 28, 28)
                        .add(jButton69)
                        .add(37, 37, 37))
                    .add(jPanel54Layout.createSequentialGroup()
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(AudSearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 157, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel54Layout.setVerticalGroup(
            jPanel54Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel54Layout.createSequentialGroup()
                .add(31, 31, 31)
                .add(jPanel54Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(AudSearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 24, Short.MAX_VALUE)
                .add(jScrollPane23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 326, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel54Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton68)
                    .add(jButton69))
                .add(38, 38, 38))
        );

        jTabbedPane17.addTab("Audit Details", jPanel54);

        org.jdesktop.layout.GroupLayout jPanel52Layout = new org.jdesktop.layout.GroupLayout(jPanel52);
        jPanel52.setLayout(jPanel52Layout);
        jPanel52Layout.setHorizontalGroup(
            jPanel52Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel52Layout.createSequentialGroup()
                .add(jTabbedPane17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 876, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 100, Short.MAX_VALUE))
        );
        jPanel52Layout.setVerticalGroup(
            jPanel52Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel52Layout.createSequentialGroup()
                .add(jTabbedPane17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 540, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane16.addTab("New Audit", jPanel52);

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel37.setText("Item Serial No");

        jTextField91.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButton70.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Save.png"))); // NOI18N
        jButton70.setText("Add");
        jButton70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton70ActionPerformed(evt);
            }
        });

        jButton71.setText(">>");

        jLabel126.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel126.setText("Name");

        jLabel127.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel127.setText("Brand");

        jLabel128.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel128.setText("Model");

        jTextField92.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField92.setEnabled(false);
        jTextField92.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField92ActionPerformed(evt);
            }
        });

        jTextField93.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField93.setEnabled(false);

        jTextField94.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField94.setEnabled(false);
        jTextField94.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField94ActionPerformed(evt);
            }
        });

        jLabel129.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel129.setText("Audit No");

        jTable17.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane24.setViewportView(jTable17);

        jLabel130.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel130.setText("Branch");

        jComboBox11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox11ActionPerformed(evt);
            }
        });

        jLabel131.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel131.setText("Current Status");

        jComboBox12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Damaged", "Missplaced", "Remaining" }));

        audNum.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        audNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audNumActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel55Layout = new org.jdesktop.layout.GroupLayout(jPanel55);
        jPanel55.setLayout(jPanel55Layout);
        jPanel55Layout.setHorizontalGroup(
            jPanel55Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel55Layout.createSequentialGroup()
                .add(38, 38, 38)
                .add(jPanel55Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel55Layout.createSequentialGroup()
                        .add(jPanel55Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel129)
                            .add(jLabel130))
                        .add(45, 45, 45)
                        .add(jPanel55Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jComboBox11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 250, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(audNum, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 250, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanel55Layout.createSequentialGroup()
                        .add(jLabel37)
                        .add(14, 14, 14)
                        .add(jTextField91, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 183, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jButton71))
                    .add(jPanel55Layout.createSequentialGroup()
                        .add(jLabel131)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jComboBox12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 219, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel55Layout.createSequentialGroup()
                        .add(jPanel55Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel55Layout.createSequentialGroup()
                                .add(jLabel126, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 96, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(4, 4, 4))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel55Layout.createSequentialGroup()
                                .add(jLabel127, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 96, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                        .add(jPanel55Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jTextField92, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .add(jTextField94)))
                    .add(jPanel55Layout.createSequentialGroup()
                        .add(jLabel128, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 96, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTextField93, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 250, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(1821, 1821, 1821)
                .add(jScrollPane24, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
            .add(jPanel55Layout.createSequentialGroup()
                .add(235, 235, 235)
                .add(jButton70)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel55Layout.setVerticalGroup(
            jPanel55Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel55Layout.createSequentialGroup()
                .add(45, 45, 45)
                .add(jPanel55Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel129)
                    .add(audNum, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel55Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jComboBox11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel130))
                .add(22, 22, 22)
                .add(jPanel55Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel37)
                    .add(jTextField91)
                    .add(jButton71, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel55Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextField92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel126))
                .add(18, 18, 18)
                .add(jPanel55Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextField94, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel127))
                .add(21, 21, 21)
                .add(jPanel55Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel128, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextField93, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(17, 17, 17)
                .add(jPanel55Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jComboBox12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel131))
                .add(26, 26, 26)
                .add(jButton70)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(jPanel55Layout.createSequentialGroup()
                .add(122, 122, 122)
                .add(jScrollPane24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 225, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        jTabbedPane16.addTab("Add Audit Items", jPanel55);

        jButton75.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton75.setText("Damaged Items");
        jButton75.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton75ActionPerformed(evt);
            }
        });

        jButton76.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton76.setText("Missplaced Items");
        jButton76.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton76ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel57Layout = new org.jdesktop.layout.GroupLayout(jPanel57);
        jPanel57.setLayout(jPanel57Layout);
        jPanel57Layout.setHorizontalGroup(
            jPanel57Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel57Layout.createSequentialGroup()
                .add(158, 158, 158)
                .add(jPanel57Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jButton76, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jButton75, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(658, Short.MAX_VALUE))
        );
        jPanel57Layout.setVerticalGroup(
            jPanel57Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel57Layout.createSequentialGroup()
                .add(82, 82, 82)
                .add(jButton75)
                .add(18, 18, 18)
                .add(jButton76)
                .addContainerGap(382, Short.MAX_VALUE))
        );

        jTabbedPane16.addTab("View Reports", jPanel57);

        searchAuditResults2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchAuditResults2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Audit", "Branch", "Item Serial No", "Name", "Brand", "Model", "Current Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane18.setViewportView(searchAuditResults2);

        Damage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Damage.setText("Damaged");

        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton1.setText("Missplaced");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton2.setText("Remaining");

        jLabel132.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel132.setText("Audit No");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel49Layout = new org.jdesktop.layout.GroupLayout(jPanel49);
        jPanel49.setLayout(jPanel49Layout);
        jPanel49Layout.setHorizontalGroup(
            jPanel49Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel49Layout.createSequentialGroup()
                .add(jPanel49Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel49Layout.createSequentialGroup()
                        .add(88, 88, 88)
                        .add(jPanel49Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jPanel49Layout.createSequentialGroup()
                                .add(Damage)
                                .add(18, 18, 18)
                                .add(jRadioButton1)
                                .add(18, 18, 18)
                                .add(jRadioButton2))
                            .add(jPanel49Layout.createSequentialGroup()
                                .add(jLabel132)
                                .add(26, 26, 26)
                                .add(jTextField1))))
                    .add(jPanel49Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jScrollPane18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 852, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel49Layout.setVerticalGroup(
            jPanel49Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel49Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel49Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel132)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(14, 14, 14)
                .add(jPanel49Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jRadioButton1)
                    .add(Damage)
                    .add(jRadioButton2))
                .add(32, 32, 32)
                .add(jScrollPane18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 375, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jTabbedPane16.addTab("Compare Audit Items", jPanel49);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 997, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jTabbedPane16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 997, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 586, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jTabbedPane16))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton67ActionPerformed

        if (AudNo.getText().isEmpty() || stDate.getDate().toString().isEmpty() || stDate.getDate().toString().isEmpty() || auditorNames.getText().isEmpty() || audNotes.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Empty Field Error.");
        } else {
            Audit a = new Audit(AudNo.getText(), stDate.getDate().toString(), stDate.getDate().toString(), auditorNames.getText(), audNotes.getText());
            AuditDAO aDAO = new AuditDAO();
            Boolean ans = aDAO.addAudit(a);
            if (ans == true) {
                JOptionPane.showMessageDialog(null, "Audit Added Successfully");
            } else {
                JOptionPane.showMessageDialog(null, "Insert Error");
            }
        }
    }//GEN-LAST:event_jButton67ActionPerformed

    private void AudNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AudNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AudNoActionPerformed

    private void jButton68ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton68ActionPerformed
        int row = searchAuditResults.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Please select a row");
        } else {
            AuditUpdate AU = new AuditUpdate(searchAuditResults.getValueAt(row, 0).toString());
            AU.setVisible(true);
        }
    }//GEN-LAST:event_jButton68ActionPerformed

    private void jButton69ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton69ActionPerformed
        // TODO add your handling code here:
        //delete audit
        int row = searchAuditResults.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Please select a row");
        } else {
            AuditDAO aDAO = new AuditDAO();
            boolean ans = aDAO.deleteAudit(searchAuditResults.getValueAt(row, 0).toString());
            if (ans == true) {
                JOptionPane.showMessageDialog(null, "Audit Deleted Successfully");
            } else {
                JOptionPane.showMessageDialog(null, "Delete Error");
            }
        }
    }//GEN-LAST:event_jButton69ActionPerformed

    private void AudSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AudSearchKeyReleased
        AuditDAO aDAO = new AuditDAO();
        AuditList = aDAO.getAuditDetails(AudSearch.getText());
        searchAuditResults.setModel(new javax.swing.table.DefaultTableModel(
                AuditList, AuditHeader));
        jScrollPane23.setViewportView(searchAuditResults);
    }//GEN-LAST:event_AudSearchKeyReleased

    private void jButton70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton70ActionPerformed
        if (audNum.getSelectedItem().toString().isEmpty() || jComboBox11.getSelectedItem().toString().isEmpty() || jTextField91.getText().isEmpty() || jTextField92.getText().isEmpty() || jTextField93.getText().isEmpty() || jTextField94.getText().isEmpty() || jComboBox12.getSelectedItem().toString().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Empty Field Error");
        } else {
            AuditItem ai = new AuditItem(audNum.getSelectedItem().toString(), jComboBox11.getSelectedItem().toString(), jTextField91.getText(), jTextField92.getText(), jTextField94.getText(), jTextField93.getText(), jComboBox12.getSelectedItem().toString());
            AuditItemDAO aiDAO = new AuditItemDAO();
            Boolean ans = aiDAO.addAudit(ai);
            if (ans == true) {
                JOptionPane.showMessageDialog(null, "Audit Item Added Successfully");
            } else {
                JOptionPane.showMessageDialog(null, "Insert Error");
            }
        }
        jComboBox11.getSelectedItem().toString();

    }//GEN-LAST:event_jButton70ActionPerformed

    private void jTextField92ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField92ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField92ActionPerformed

    private void jTextField94ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField94ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField94ActionPerformed

    private void jComboBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox11ActionPerformed

    private void audNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_audNumActionPerformed

    private void jButton75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton75ActionPerformed
        String stat = "Damaged";
        ReportViewer viewr = new ReportViewer();
        HashMap hmp = new HashMap();
        hmp.put("status", stat);
        viewr.showReport("AuditItemReport.jrxml", hmp);
    }//GEN-LAST:event_jButton75ActionPerformed

    private void jButton76ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton76ActionPerformed
        String stat = "Missplaced";
        ReportViewer viewr = new ReportViewer();
        HashMap hmp = new HashMap();
        hmp.put("status", stat);
        viewr.showReport("AuditItemReport.jrxml", hmp);
    }//GEN-LAST:event_jButton76ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        String type = "";
        if (Damage.isSelected()) {
            type = "damaged";
        } else if (jRadioButton1.isSelected()) {
            type = "Missplaced";
        } else if (jRadioButton2.isSelected()) {
            type = "Remaining";
        }
        AuditItemDAO aiDAO = new AuditItemDAO();
        AuditList2 = aiDAO.getAuditItemDetails(jTextField1.getText(), type);
        searchAuditResults2.setModel(new javax.swing.table.DefaultTableModel(
                AuditList2, AuditHeader2));
        jScrollPane18.setViewportView(searchAuditResults2);

    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTabbedPane16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane16MouseClicked
        LoadIDS();
        LoadBranches();
    }//GEN-LAST:event_jTabbedPane16MouseClicked

    private void LoadIDS() {
        ArrayList temp;
        AuditDAO aDAO = new AuditDAO();
        temp = aDAO.getAuditIDS();
        audNum.removeAllItems();
        Iterator i = temp.iterator();

        while (i.hasNext()) {
            audNum.addItem(i.next());
        }
    }

    private void LoadBranches() {
        ArrayList temp;
        AuditDAO aDAO = new AuditDAO();
        temp = aDAO.getBranches();
        jComboBox11.removeAllItems();
        Iterator i = temp.iterator();

        while (i.hasNext()) {
            jComboBox11.addItem(i.next());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AudNo;
    private javax.swing.JTextField AudSearch;
    private javax.swing.JRadioButton Damage;
    private javax.swing.JTextPane audNotes;
    private javax.swing.JComboBox audNum;
    private javax.swing.JTextArea auditorNames;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JComboBox jComboBox11;
    private javax.swing.JComboBox jComboBox12;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JTabbedPane jTabbedPane16;
    private javax.swing.JTabbedPane jTabbedPane17;
    private javax.swing.JTable jTable17;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField91;
    private javax.swing.JTextField jTextField92;
    private javax.swing.JTextField jTextField93;
    private javax.swing.JTextField jTextField94;
    private javax.swing.JTable searchAuditResults;
    private javax.swing.JTable searchAuditResults2;
    private com.toedter.calendar.JDateChooser stDate;
    // End of variables declaration//GEN-END:variables
}
