/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package OrganizedIn.UI;

import OrganizedIn.Data.DataAccess;
import OrganizedIn.Lib.ComboItem;
import OrganizedIn.Lib.Feedback;
import OrganizedIn.Lib.Help.HIGHLIGHT;
import OrganizedIn.Lib.Helper.HelperHelpdesk;
import OrganizedIn.Lib.Help.Message;
import OrganizedIn.Lib.Help.MessageCell;
import OrganizedIn.Lib.Help.MessageTableModel;
import OrganizedIn.Lib.OrgSystem;
import OrganizedIn.Lib.Help.PRIORITY;
import OrganizedIn.Lib.Help.Ticket;
import OrganizedIn.Lib.Helper.SearchListner;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 *
 * @author gamunu
 */
public class HelpDeskPanel extends javax.swing.JPanel {

    private static Logger logger = LogManager.getLogger(DataAccess.class.getName());
    int replyTicketId;

    /**
     * Creates new form HelpDesk
     */
    public HelpDeskPanel() {
        initComponents();
        Help_TabbedPane.remove(1);

        // Listen for changes in the text
        helpSearchText.getDocument().addDocumentListener(new SearchListner(this));

        // Autoscroll to bottom ...
        //jScrollPane2.getVerticalScrollBar().addAdjustmentListener(new AdjustmentListener() {  
        //  @Override
        //  public void adjustmentValueChanged(AdjustmentEvent e) {  
        //    e.getAdjustable().setValue(e.getAdjustable().getMaximum());  
        //   }
        // });

    }

    public int getReplyTicketId() {
        return replyTicketId;
    }

    public void setReplyTicketId(int replyTicketId) {
        this.replyTicketId = replyTicketId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Help_TabbedPane = new javax.swing.JTabbedPane();
        Help_Tickers = new javax.swing.JPanel();
        Help_TickersRefreshBtn = new javax.swing.JButton();
        Help_TicketsSloveBtn = new javax.swing.JButton();
        Help_TicketsCloseBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Help_TicketsTicketList = new javax.swing.JTable();
        filterTicketPriority = new javax.swing.JComboBox();
        jLabel138 = new javax.swing.JLabel();
        helpSearchText = new javax.swing.JTextField();
        Help_Reply = new javax.swing.JPanel();
        jScrollPane25 = new javax.swing.JScrollPane();
        Help_ReplyMessageTxt = new javax.swing.JTextArea();
        Help_ReplyReplyBtn = new javax.swing.JButton();
        Help_TicketTicketClose = new javax.swing.JButton();
        jLabel135 = new javax.swing.JLabel();
        jLabel136 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Help_TicketsMessageList = new javax.swing.JTable();
        Help_TicketMessageDelete1 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        Help_TicketSubjectTxt = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        Help_TicketMessageTxt = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        Help_TicketMessageTxt1 = new javax.swing.JTextArea();
        jLabel137 = new javax.swing.JLabel();
        jPanel56 = new javax.swing.JPanel();
        jLabel132 = new javax.swing.JLabel();
        jLabel133 = new javax.swing.JLabel();
        jLabel134 = new javax.swing.JLabel();
        jScrollPane26 = new javax.swing.JScrollPane();
        Help_CreateMessageTxt = new javax.swing.JTextArea();
        Help_CreatePriorityCmb = new javax.swing.JComboBox();
        Help_CreateSubjectTxt = new javax.swing.JTextField();
        Help_CreateCreateBtn = new javax.swing.JButton();
        jPanel59 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Help_SolvedTicketList = new javax.swing.JTable();
        jPanel60 = new javax.swing.JPanel();
        Help_TabbedClosedReopen = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        Help_ClosedTicketList = new javax.swing.JTable();
        Feedback = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        helpFeedBackTbl = new javax.swing.JTable();
        helpFeedbackDeleteBtn = new javax.swing.JButton();
        helpFeedbackAcceptBtn = new javax.swing.JButton();
        helpFeedbackAcceptBtn1 = new javax.swing.JButton();
        helpFeedbackDeleteBtn1 = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(876, 523));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(876, 523));

        Help_TickersRefreshBtn.setText("Reload");
        Help_TickersRefreshBtn.setMaximumSize(new java.awt.Dimension(113, 29));
        Help_TickersRefreshBtn.setMinimumSize(new java.awt.Dimension(113, 29));
        Help_TickersRefreshBtn.setPreferredSize(new java.awt.Dimension(113, 29));
        Help_TickersRefreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Help_TickersRefreshBtnActionPerformed(evt);
            }
        });

        Help_TicketsSloveBtn.setText("Set as Solved");
        Help_TicketsSloveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Help_TicketsSloveBtnActionPerformed(evt);
            }
        });

        Help_TicketsCloseBtn.setText("Set as Closed");
        Help_TicketsCloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Help_TicketsCloseBtnActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setDoubleBuffered(true);
        jScrollPane1.setHorizontalScrollBar(null);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(469, 200));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(469, 200));

        Help_TicketsTicketList.setDoubleBuffered(true);
        Help_TicketsTicketList.setMinimumSize(new java.awt.Dimension(593, 437));
        Help_TicketsTicketList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Help_TicketsTicketList.setTableHeader(null);
        Help_TicketsTicketList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Help_TicketsTicketListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Help_TicketsTicketList);

        filterTicketPriority.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filterTicketPriorityItemStateChanged(evt);
            }
        });
        filterTicketPriority.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterTicketPriorityActionPerformed(evt);
            }
        });

        jLabel138.setText("Filter");

        helpSearchText.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        javax.swing.GroupLayout Help_TickersLayout = new javax.swing.GroupLayout(Help_Tickers);
        Help_Tickers.setLayout(Help_TickersLayout);
        Help_TickersLayout.setHorizontalGroup(
            Help_TickersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Help_TickersLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(helpSearchText, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(jLabel138, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filterTicketPriority, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 354, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Help_TickersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Help_TickersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Help_TicketsCloseBtn)
                    .addComponent(Help_TicketsSloveBtn)
                    .addComponent(Help_TickersRefreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(126, 126, 126))
        );
        Help_TickersLayout.setVerticalGroup(
            Help_TickersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Help_TickersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Help_TickersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel138)
                    .addComponent(filterTicketPriority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(helpSearchText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(Help_TickersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Help_TickersLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(Help_TicketsCloseBtn)
                        .addGap(18, 18, 18)
                        .addComponent(Help_TicketsSloveBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Help_TickersRefreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Help_TickersLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        Help_TabbedPane.addTab("Tickets", new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Help.png")), Help_Tickers); // NOI18N

        Help_ReplyMessageTxt.setColumns(20);
        Help_ReplyMessageTxt.setRows(5);
        jScrollPane25.setViewportView(Help_ReplyMessageTxt);

        Help_ReplyReplyBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Mail.png"))); // NOI18N
        Help_ReplyReplyBtn.setText("Reply");
        Help_ReplyReplyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Help_ReplyReplyBtnActionPerformed(evt);
            }
        });

        Help_TicketTicketClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/back.png"))); // NOI18N
        Help_TicketTicketClose.setText("Close");
        Help_TicketTicketClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Help_TicketTicketCloseActionPerformed(evt);
            }
        });

        jLabel135.setText("Message:");

        jLabel136.setText("Subject:");

        Help_TicketsMessageList.setDoubleBuffered(true);
        Help_TicketsMessageList.setMinimumSize(new java.awt.Dimension(593, 230));
        Help_TicketsMessageList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Help_TicketsMessageList.setTableHeader(null);
        jScrollPane2.setViewportView(Help_TicketsMessageList);

        Help_TicketMessageDelete1.setText("Delete");
        Help_TicketMessageDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Help_TicketMessageDelete1ActionPerformed(evt);
            }
        });

        Help_TicketSubjectTxt.setEditable(false);
        Help_TicketSubjectTxt.setColumns(20);
        Help_TicketSubjectTxt.setLineWrap(true);
        Help_TicketSubjectTxt.setRows(5);
        Help_TicketSubjectTxt.setWrapStyleWord(true);
        Help_TicketSubjectTxt.setAutoscrolls(false);
        jScrollPane6.setViewportView(Help_TicketSubjectTxt);

        Help_TicketMessageTxt.setEditable(false);
        Help_TicketMessageTxt.setColumns(20);
        Help_TicketMessageTxt.setLineWrap(true);
        Help_TicketMessageTxt.setRows(5);
        Help_TicketMessageTxt.setWrapStyleWord(true);
        Help_TicketMessageTxt.setAutoscrolls(false);
        Help_TicketMessageTxt.setDragEnabled(false);
        jScrollPane7.setViewportView(Help_TicketMessageTxt);

        Help_TicketMessageTxt1.setEditable(false);
        Help_TicketMessageTxt1.setColumns(20);
        Help_TicketMessageTxt1.setLineWrap(true);
        Help_TicketMessageTxt1.setRows(5);
        Help_TicketMessageTxt1.setWrapStyleWord(true);
        Help_TicketMessageTxt1.setAutoscrolls(false);
        jScrollPane8.setViewportView(Help_TicketMessageTxt1);

        jLabel137.setText("User Details:");

        javax.swing.GroupLayout Help_ReplyLayout = new javax.swing.GroupLayout(Help_Reply);
        Help_Reply.setLayout(Help_ReplyLayout);
        Help_ReplyLayout.setHorizontalGroup(
            Help_ReplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Help_ReplyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Help_ReplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
                    .addComponent(jScrollPane25, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
                    .addGroup(Help_ReplyLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Help_TicketMessageDelete1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Help_ReplyReplyBtn)
                        .addGap(18, 18, 18)
                        .addComponent(Help_TicketTicketClose)
                        .addGap(6, 6, 6)))
                .addGap(29, 29, 29)
                .addGroup(Help_ReplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel136)
                    .addComponent(jLabel135)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel137))
                .addGap(62, 62, 62))
        );
        Help_ReplyLayout.setVerticalGroup(
            Help_ReplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Help_ReplyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Help_ReplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Help_ReplyLayout.createSequentialGroup()
                        .addComponent(jLabel136)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel135)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel137)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Help_ReplyLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(Help_ReplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Help_TicketMessageDelete1)
                            .addComponent(Help_ReplyReplyBtn)
                            .addComponent(Help_TicketTicketClose))))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        Help_TabbedPane.addTab("Ticket", new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Mail.png")), Help_Reply); // NOI18N

        jLabel132.setLabelFor(Help_CreateSubjectTxt);
        jLabel132.setText("Subject");

        jLabel133.setLabelFor(Help_CreateMessageTxt);
        jLabel133.setText("Message");

        jLabel134.setLabelFor(Help_CreatePriorityCmb);
        jLabel134.setText("Priority");

        Help_CreateMessageTxt.setColumns(20);
        Help_CreateMessageTxt.setRows(5);
        Help_CreateMessageTxt.setText("Enter message here..");
        jScrollPane26.setViewportView(Help_CreateMessageTxt);

        Help_CreateSubjectTxt.setText("Enter subject here..");
        Help_CreateSubjectTxt.setToolTipText("");

        Help_CreateCreateBtn.setText("Create");
        Help_CreateCreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Help_CreateCreateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel56Layout = new javax.swing.GroupLayout(jPanel56);
        jPanel56.setLayout(jPanel56Layout);
        jPanel56Layout.setHorizontalGroup(
            jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel56Layout.createSequentialGroup()
                .addGroup(jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel56Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Help_CreateCreateBtn))
                    .addGroup(jPanel56Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel56Layout.createSequentialGroup()
                                .addComponent(jLabel133)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane26))
                            .addGroup(jPanel56Layout.createSequentialGroup()
                                .addGroup(jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel56Layout.createSequentialGroup()
                                        .addComponent(jLabel134)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Help_CreatePriorityCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel56Layout.createSequentialGroup()
                                        .addComponent(jLabel132)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Help_CreateSubjectTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)))
                                .addGap(269, 269, 269)))))
                .addGap(151, 151, 151))
        );
        jPanel56Layout.setVerticalGroup(
            jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel56Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel132)
                    .addComponent(Help_CreateSubjectTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel134)
                    .addComponent(Help_CreatePriorityCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel133)
                    .addComponent(jScrollPane26, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(Help_CreateCreateBtn)
                .addGap(54, 54, 54))
        );

        Help_TabbedPane.addTab("Create", new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Recent Items.png")), jPanel56); // NOI18N

        jButton9.setText("Reopen");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        Help_SolvedTicketList.setDoubleBuffered(true);
        Help_SolvedTicketList.setMinimumSize(new java.awt.Dimension(593, 437));
        Help_SolvedTicketList.setPreferredSize(new java.awt.Dimension(593, 437));
        Help_SolvedTicketList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Help_SolvedTicketList.setTableHeader(null);
        jScrollPane3.setViewportView(Help_SolvedTicketList);

        javax.swing.GroupLayout jPanel59Layout = new javax.swing.GroupLayout(jPanel59);
        jPanel59.setLayout(jPanel59Layout);
        jPanel59Layout.setHorizontalGroup(
            jPanel59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel59Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton9)
                .addGap(166, 166, 166))
        );
        jPanel59Layout.setVerticalGroup(
            jPanel59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel59Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel59Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jButton9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Help_TabbedPane.addTab("Solved", new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/System.png")), jPanel59); // NOI18N

        Help_TabbedClosedReopen.setText("Reopen");
        Help_TabbedClosedReopen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Help_TabbedClosedReopenActionPerformed(evt);
            }
        });

        Help_ClosedTicketList.setDoubleBuffered(true);
        Help_ClosedTicketList.setMinimumSize(new java.awt.Dimension(593, 437));
        Help_ClosedTicketList.setName(""); // NOI18N
        Help_ClosedTicketList.setPreferredSize(new java.awt.Dimension(593, 437));
        Help_ClosedTicketList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Help_ClosedTicketList.setTableHeader(null);
        jScrollPane4.setViewportView(Help_ClosedTicketList);

        javax.swing.GroupLayout jPanel60Layout = new javax.swing.GroupLayout(jPanel60);
        jPanel60.setLayout(jPanel60Layout);
        jPanel60Layout.setHorizontalGroup(
            jPanel60Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel60Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Help_TabbedClosedReopen)
                .addGap(166, 166, 166))
        );
        jPanel60Layout.setVerticalGroup(
            jPanel60Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel60Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel60Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                    .addGroup(jPanel60Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(Help_TabbedClosedReopen)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        Help_TabbedPane.addTab("Closed", new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Default Programs.png")), jPanel60); // NOI18N

        helpFeedBackTbl.setDoubleBuffered(true);
        helpFeedBackTbl.setMinimumSize(new java.awt.Dimension(593, 437));
        helpFeedBackTbl.setName(""); // NOI18N
        helpFeedBackTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        helpFeedBackTbl.setTableHeader(null);
        jScrollPane5.setViewportView(helpFeedBackTbl);

        helpFeedbackDeleteBtn.setText("Delete");
        helpFeedbackDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpFeedbackDeleteBtnActionPerformed(evt);
            }
        });

        helpFeedbackAcceptBtn.setText("Accept");
        helpFeedbackAcceptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpFeedbackAcceptBtnActionPerformed(evt);
            }
        });

        helpFeedbackAcceptBtn1.setText("Decline");
        helpFeedbackAcceptBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpFeedbackAcceptBtn1ActionPerformed(evt);
            }
        });

        helpFeedbackDeleteBtn1.setText("Reload");
        helpFeedbackDeleteBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpFeedbackDeleteBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FeedbackLayout = new javax.swing.GroupLayout(Feedback);
        Feedback.setLayout(FeedbackLayout);
        FeedbackLayout.setHorizontalGroup(
            FeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FeedbackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(FeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(helpFeedbackAcceptBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(helpFeedbackAcceptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(helpFeedbackDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(helpFeedbackDeleteBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(150, 150, 150))
        );
        FeedbackLayout.setVerticalGroup(
            FeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FeedbackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(FeedbackLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(helpFeedbackAcceptBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(helpFeedbackAcceptBtn1)
                .addGap(18, 18, 18)
                .addComponent(helpFeedbackDeleteBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(helpFeedbackDeleteBtn1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Help_TabbedPane.addTab("Feedback", new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Brightness.png")), Feedback); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Help_TabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Help_TabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Help_TickersRefreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Help_TickersRefreshBtnActionPerformed
        // TODO add your handling code here:
        HelperHelpdesk.loadTickets(this);
    }//GEN-LAST:event_Help_TickersRefreshBtnActionPerformed

    private void Help_ReplyReplyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Help_ReplyReplyBtnActionPerformed
        // TODO add your handling code here
        HelperHelpdesk.replyToMessage(this);
    }//GEN-LAST:event_Help_ReplyReplyBtnActionPerformed

    private void Help_TicketTicketCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Help_TicketTicketCloseActionPerformed
        // TODO add your handling code here:
        Help_TabbedPane.remove(1);
    }//GEN-LAST:event_Help_TicketTicketCloseActionPerformed

    private void Help_CreateCreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Help_CreateCreateBtnActionPerformed
        // TODO add your handling code here:
        String subject = Help_CreateSubjectTxt.getText();
        String message = Help_CreateMessageTxt.getText();
        ComboItem priority = (ComboItem) Help_CreatePriorityCmb.getSelectedItem();
        if (!(subject.isEmpty() && message.isEmpty())) {
            int it = Ticket.createTicket(subject, message, PRIORITY.valueOf(priority.getValue()));
            if (it > 0) {
                Ticket.changeOwnerHighlight(HIGHLIGHT.Y, it);
                JOptionPane.showMessageDialog(this, "Ticket created wait for a reply", "Success", JOptionPane.INFORMATION_MESSAGE);
                HelperHelpdesk.loadTickets(this);
            } else {
                JOptionPane.showMessageDialog(this, "Ticket creation failed, Why don't you try agin", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Did you miss something? Please fill information to continue.", "Falied", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_Help_CreateCreateBtnActionPerformed

    private void Help_TicketsCloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Help_TicketsCloseBtnActionPerformed
        // TODO add your handling code here:
        HelperHelpdesk.setTicketClosed(this);
    }//GEN-LAST:event_Help_TicketsCloseBtnActionPerformed

    private void Help_TicketsSloveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Help_TicketsSloveBtnActionPerformed
        // TODO add your handling code here:
        HelperHelpdesk.setTicketSolved(this);
    }//GEN-LAST:event_Help_TicketsSloveBtnActionPerformed

    private void Help_TabbedClosedReopenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Help_TabbedClosedReopenActionPerformed
        // TODO add your handling code here:
        HelperHelpdesk.closedReopen(this);
    }//GEN-LAST:event_Help_TabbedClosedReopenActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        HelperHelpdesk.solvedReopen(this);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void Help_TicketsTicketListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Help_TicketsTicketListMouseClicked
        Ticket o = (Ticket) Help_TicketsTicketList.getModel().getValueAt(Help_TicketsTicketList.getSelectedRow(), 0);

        int index = -1;

        switch (o.getPriority()) {
            case high:
                index = 0;
                break;
            case medium:
                index = 1;
                break;
            case low:
                index = 2;
        }

        Help_TicketsMessageList.setDefaultRenderer(Message.class, new MessageCell());
        if (evt.getClickCount() == 2) {
            if (OrgSystem.User.hasPrivilege("view:message")) {
                System.out.println("Double-clicked on: " + o.getTicketid());
                Help_TabbedPane.insertTab("Ticket", new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/System.png")), Help_Reply, null, 1);

                //Messages display
                try (Connection conn = DataAccess.getConnection();
                        Statement stmt = conn.createStatement();
                        ResultSet result = stmt.executeQuery("SELECT subject,message FROM ticket WHERE ticketid=" + o.getTicketid())) {

                    if (result.next()) {
                        String subject = result.getString("subject");
                        String message = result.getString("message");

                        Help_TicketSubjectTxt.setText(subject);
                        Help_TicketMessageTxt1.setText(message);
                        Help_TicketMessageTxt.setText(o.getOwnerDetails());
                        replyTicketId = o.getTicketid();
                    }
                } catch (SQLException ex) {
                    logger.error("Function: mouseClicked listener in Class: HelpMain\n Something Went Wrong\n: " + ex);
                }
                MessageTableModel messageModel = new MessageTableModel(o.getMesssages());
                Help_TicketsMessageList.setModel(messageModel);
            } else {
                JOptionPane.showMessageDialog(this, "You don't have sufficient privileges", "Warning!", JOptionPane.WARNING_MESSAGE);
            }
        }

    }//GEN-LAST:event_Help_TicketsTicketListMouseClicked

    private void Help_TicketMessageDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Help_TicketMessageDelete1ActionPerformed
        // TODO add your handling code here
        HelperHelpdesk.deleteMessage(this);
    }//GEN-LAST:event_Help_TicketMessageDelete1ActionPerformed

    private void helpFeedbackAcceptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpFeedbackAcceptBtnActionPerformed
        // TODO add your handling code here:
        HelperHelpdesk.acceptFeedback(this);
    }//GEN-LAST:event_helpFeedbackAcceptBtnActionPerformed

    private void helpFeedbackDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpFeedbackDeleteBtnActionPerformed
        // TODO add your handling code here:
        Feedback o = (Feedback) helpFeedBackTbl.getModel().getValueAt(helpFeedBackTbl.getSelectedRow(), 0);
        if (o.deleteFeedback()) {
            //Reload Tables
            JOptionPane.showMessageDialog(this, "Feedback Message Successfully deleted");
            HelperHelpdesk.loadTickets(this);
            HelperHelpdesk.loadSlovedTickets(this);
            HelperHelpdesk.loadClosedTickets(this);
            HelperHelpdesk.loadFeedbackMessages(this);
        } else {
        }
    }//GEN-LAST:event_helpFeedbackDeleteBtnActionPerformed

    private void filterTicketPriorityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterTicketPriorityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filterTicketPriorityActionPerformed

    private void filterTicketPriorityItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filterTicketPriorityItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.DESELECTED) {
            HelperHelpdesk.loadTickets(this, helpSearchText.getText(), PRIORITY.valueOf(ComboItem.getValue(filterTicketPriority.getSelectedItem())));
        }
    }//GEN-LAST:event_filterTicketPriorityItemStateChanged

    private void helpFeedbackAcceptBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpFeedbackAcceptBtn1ActionPerformed
        // TODO add your handling code here:
        HelperHelpdesk.acceptFeedback(this);
    }//GEN-LAST:event_helpFeedbackAcceptBtn1ActionPerformed

    private void helpFeedbackDeleteBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpFeedbackDeleteBtn1ActionPerformed
        // TODO add your handling code here:
        HelperHelpdesk.declineFeedback(this);
    }//GEN-LAST:event_helpFeedbackDeleteBtn1ActionPerformed

    public void removeHelpTicketTab() {
        Help_TabbedPane.remove(1);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel Feedback;
    public javax.swing.JTable Help_ClosedTicketList;
    public javax.swing.JButton Help_CreateCreateBtn;
    public javax.swing.JTextArea Help_CreateMessageTxt;
    public javax.swing.JComboBox Help_CreatePriorityCmb;
    public javax.swing.JTextField Help_CreateSubjectTxt;
    public javax.swing.JPanel Help_Reply;
    public javax.swing.JTextArea Help_ReplyMessageTxt;
    public javax.swing.JButton Help_ReplyReplyBtn;
    public javax.swing.JTable Help_SolvedTicketList;
    public javax.swing.JButton Help_TabbedClosedReopen;
    public javax.swing.JTabbedPane Help_TabbedPane;
    public javax.swing.JPanel Help_Tickers;
    public javax.swing.JButton Help_TickersRefreshBtn;
    public javax.swing.JButton Help_TicketMessageDelete1;
    public javax.swing.JTextArea Help_TicketMessageTxt;
    public javax.swing.JTextArea Help_TicketMessageTxt1;
    public javax.swing.JTextArea Help_TicketSubjectTxt;
    public javax.swing.JButton Help_TicketTicketClose;
    public javax.swing.JButton Help_TicketsCloseBtn;
    public javax.swing.JTable Help_TicketsMessageList;
    public javax.swing.JButton Help_TicketsSloveBtn;
    public javax.swing.JTable Help_TicketsTicketList;
    public javax.swing.JComboBox filterTicketPriority;
    public javax.swing.JTable helpFeedBackTbl;
    public javax.swing.JButton helpFeedbackAcceptBtn;
    public javax.swing.JButton helpFeedbackAcceptBtn1;
    public javax.swing.JButton helpFeedbackDeleteBtn;
    public javax.swing.JButton helpFeedbackDeleteBtn1;
    public javax.swing.JTextField helpSearchText;
    public javax.swing.JButton jButton9;
    public javax.swing.JLabel jLabel132;
    public javax.swing.JLabel jLabel133;
    public javax.swing.JLabel jLabel134;
    public javax.swing.JLabel jLabel135;
    public javax.swing.JLabel jLabel136;
    public javax.swing.JLabel jLabel137;
    public javax.swing.JLabel jLabel138;
    public javax.swing.JPanel jPanel56;
    public javax.swing.JPanel jPanel59;
    public javax.swing.JPanel jPanel60;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane25;
    public javax.swing.JScrollPane jScrollPane26;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JScrollPane jScrollPane7;
    public javax.swing.JScrollPane jScrollPane8;
    // End of variables declaration//GEN-END:variables
}
