/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package OrganizedIn.UI;

import OrganizedIn.Lib.ComboItem;
import OrganizedIn.Lib.Helper.HelperInventory;
import OrganizedIn.Lib.Inventory;
import OrganizedIn.Lib.OrgSystem;
import OrganizedIn.Lib.ReportViewer;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author gamunu
 */
public class InventoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form InventoryPanel
     */
    public InventoryPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Inven_InvenTlbl = new javax.swing.JTable();
        Inven_InvenUpdateBtn = new javax.swing.JButton();
        Inven_InvenDeleteBtn = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        Inven_ManageLapSerialTxt = new javax.swing.JTabbedPane();
        jPanel17 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        Inven_ManagePcNameTxt = new javax.swing.JTextField();
        Inven_ManagePcModelTxt = new javax.swing.JTextField();
        Inven_ManagePcBrandTxt = new javax.swing.JTextField();
        Inven_ManagePcAddBtn = new javax.swing.JButton();
        Inven_ManagePcProceTxt = new javax.swing.JTextField();
        Inven_ManagePcRamTxt = new javax.swing.JTextField();
        Inven_ManagePcHardTxt = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        Inven_ManagePcUpdBtn = new javax.swing.JButton();
        Inven_ManagePcSupNameCbx = new javax.swing.JComboBox();
        Inven_ManagePcBranNameCbx = new javax.swing.JComboBox();
        Inven_ManagePCSerialNoCbx = new javax.swing.JComboBox();
        jPanel34 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        Inven_ManagePrinNameTxt = new javax.swing.JTextField();
        Inven_ManagePrinBrandTxt = new javax.swing.JTextField();
        Inven_ManagePrinModelTxt = new javax.swing.JTextField();
        Inven_ManagePrinUpsTxt = new javax.swing.JTextField();
        Inven_ManagePrinterAddBtn = new javax.swing.JButton();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        Inven_ManagePrinTypeCbx = new javax.swing.JComboBox();
        Inven_ManagePriBranNameCbx = new javax.swing.JComboBox();
        Inven_ManagePrinSupNameCbx = new javax.swing.JComboBox();
        Inven_ManagePrinFrontCbx = new javax.swing.JComboBox();
        Inven_ManagePrinSerialNoCbx = new javax.swing.JComboBox();
        jPanel35 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        Inven_ManageLapNameTxt = new javax.swing.JTextField();
        Inven_ManageLapModelTxt = new javax.swing.JTextField();
        Inven_ManageLapBrandTxt = new javax.swing.JTextField();
        Inven_ManageLapAddBtn = new javax.swing.JButton();
        Inven_ManageLapProceTxt = new javax.swing.JTextField();
        Inven_ManageLapRamTxt = new javax.swing.JTextField();
        Inven_ManageLapHardTxt = new javax.swing.JTextField();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jButton60 = new javax.swing.JButton();
        Inven_ManageLapBranNameCbx = new javax.swing.JComboBox();
        Inven_ManageLapSupNameCbx = new javax.swing.JComboBox();
        Inven_ManageLapSerialNoCbx = new javax.swing.JComboBox();
        jPanel37 = new javax.swing.JPanel();
        jLabel81 = new javax.swing.JLabel();
        Inven_ManageOtherBrandTxt = new javax.swing.JTextField();
        jButton61 = new javax.swing.JButton();
        Inven_ManageOtherNameTxt = new javax.swing.JTextField();
        Inven_ManageOtherModelTxt = new javax.swing.JTextField();
        jButton35 = new javax.swing.JButton();
        jLabel83 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Inven_ManageOthSupNameCbx = new javax.swing.JComboBox();
        Inven_ManageOthBranNameCbx = new javax.swing.JComboBox();
        Inven_ManageOtherSerialNoCbx = new javax.swing.JComboBox();
        jPanel39 = new javax.swing.JPanel();
        jButton36 = new javax.swing.JButton();
        Inven_ReportTypeCbx = new javax.swing.JComboBox();
        jLabel84 = new javax.swing.JLabel();
        jPanel40 = new javax.swing.JPanel();
        jLabel85 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        user_txt = new javax.swing.JTextField();
        position_txt = new javax.swing.JTextField();
        jButton37 = new javax.swing.JButton();
        type_txt = new javax.swing.JTextField();
        jLabel123 = new javax.swing.JLabel();
        Inven_AssgnUsrSerialNoCbx = new javax.swing.JComboBox();
        jPanel41 = new javax.swing.JPanel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jTextField65 = new javax.swing.JTextField();
        jButton38 = new javax.swing.JButton();
        jLabel124 = new javax.swing.JLabel();
        jTextField89 = new javax.swing.JTextField();
        jLabel125 = new javax.swing.JLabel();
        Inven_AssgnPartSerialNoCbx = new javax.swing.JComboBox();

        setMinimumSize(new java.awt.Dimension(879, 513));

        jTabbedPane3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane3.setMinimumSize(new java.awt.Dimension(879, 513));
        jTabbedPane3.setOpaque(true);

        jPanel9.setMinimumSize(new java.awt.Dimension(740, 479));
        jPanel9.setPreferredSize(new java.awt.Dimension(740, 479));

        jScrollPane4.setMinimumSize(new java.awt.Dimension(854, 326));
        jScrollPane4.setPreferredSize(new java.awt.Dimension(854, 326));

        Inven_InvenTlbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Inven_InvenTlbl.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        Inven_InvenTlbl.setDoubleBuffered(true);
        jScrollPane4.setViewportView(Inven_InvenTlbl);

        Inven_InvenUpdateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Update.png"))); // NOI18N
        Inven_InvenUpdateBtn.setText("Update");
        Inven_InvenUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inven_InvenUpdateBtnActionPerformed(evt);
            }
        });

        Inven_InvenDeleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Recycle Bin Full.png"))); // NOI18N
        Inven_InvenDeleteBtn.setText("Delete");
        Inven_InvenDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inven_InvenDeleteBtnActionPerformed(evt);
            }
        });

        jLabel32.setText("Inventory");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(64, 64, 64))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(604, Short.MAX_VALUE)
                .addComponent(Inven_InvenUpdateBtn)
                .addGap(18, 18, 18)
                .addComponent(Inven_InvenDeleteBtn)
                .addGap(123, 123, 123))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel32)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Inven_InvenUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Inven_InvenDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Inventory", new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Info.png")), jPanel9); // NOI18N

        jPanel8.setMinimumSize(new java.awt.Dimension(740, 479));
        jPanel8.setPreferredSize(new java.awt.Dimension(740, 479));

        jLabel8.setText("Serial Number");

        jLabel42.setText("Name");

        jLabel43.setText("Brand");

        jLabel58.setText("Model");

        jLabel59.setText("Processor");

        jLabel60.setText("RAM");

        jLabel61.setText("Hard Disk");

        Inven_ManagePcBrandTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inven_ManagePcBrandTxtActionPerformed(evt);
            }
        });

        Inven_ManagePcAddBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Update.png"))); // NOI18N
        Inven_ManagePcAddBtn.setText("Add");
        Inven_ManagePcAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inven_ManagePcAddBtnActionPerformed(evt);
            }
        });

        Inven_ManagePcProceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inven_ManagePcProceTxtActionPerformed(evt);
            }
        });

        jLabel68.setText("Supplier Name");

        jLabel69.setText("Branch Name");

        Inven_ManagePcUpdBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Update.png"))); // NOI18N
        Inven_ManagePcUpdBtn.setText("Update");
        Inven_ManagePcUpdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inven_ManagePcUpdBtnActionPerformed(evt);
            }
        });

        Inven_ManagePCSerialNoCbx.setEditable(true);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(Inven_ManagePcBrandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(Inven_ManagePcModelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(Inven_ManagePcProceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(Inven_ManagePcRamTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(Inven_ManagePcAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(Inven_ManagePcUpdBtn))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Inven_ManagePcHardTxt)
                            .addComponent(Inven_ManagePcSupNameCbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Inven_ManagePcBranNameCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Inven_ManagePcNameTxt)
                            .addComponent(Inven_ManagePCSerialNoCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(467, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Inven_ManagePCSerialNoCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(Inven_ManagePcNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel43))
                    .addComponent(Inven_ManagePcBrandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel58)
                    .addComponent(Inven_ManagePcModelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel59))
                    .addComponent(Inven_ManagePcProceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel60))
                    .addComponent(Inven_ManagePcRamTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel61))
                    .addComponent(Inven_ManagePcHardTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel68)
                    .addComponent(Inven_ManagePcSupNameCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel69)
                    .addComponent(Inven_ManagePcBranNameCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Inven_ManagePcAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Inven_ManagePcUpdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        Inven_ManageLapSerialTxt.addTab("PC", jPanel17);

        jLabel9.setText("Serial Number");

        jLabel62.setText("Name");

        jLabel63.setText("Brand");

        jLabel64.setText("Model");

        jLabel65.setText("Type");

        jLabel5.setText("F.Front");

        jLabel66.setText("UPS");

        Inven_ManagePrinterAddBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Save.png"))); // NOI18N
        Inven_ManagePrinterAddBtn.setText("Add");
        Inven_ManagePrinterAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inven_ManagePrinterAddBtnActionPerformed(evt);
            }
        });

        jLabel70.setText("Supplier Name");

        jLabel71.setText("Branch Name");

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Update.png"))); // NOI18N
        jButton17.setText("Update");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel34Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(Inven_ManagePrinterAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton17))
                    .addGroup(jPanel34Layout.createSequentialGroup()
                        .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel70, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel71))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Inven_ManagePriBranNameCbx, 0, 230, Short.MAX_VALUE)
                            .addComponent(Inven_ManagePrinSupNameCbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel34Layout.createSequentialGroup()
                        .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel34Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel5)))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Inven_ManagePrinUpsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Inven_ManagePrinFrontCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel34Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel34Layout.createSequentialGroup()
                                .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(Inven_ManagePrinBrandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel34Layout.createSequentialGroup()
                                .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(Inven_ManagePrinModelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel34Layout.createSequentialGroup()
                                .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(Inven_ManagePrinTypeCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel34Layout.createSequentialGroup()
                                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Inven_ManagePrinNameTxt)
                                    .addComponent(Inven_ManagePrinSerialNoCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(487, Short.MAX_VALUE))
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Inven_ManagePrinSerialNoCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel34Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel62))
                    .addComponent(Inven_ManagePrinNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel63)
                    .addGroup(jPanel34Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(Inven_ManagePrinBrandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel64)
                    .addGroup(jPanel34Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(Inven_ManagePrinModelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel65)
                    .addComponent(Inven_ManagePrinTypeCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Inven_ManagePrinFrontCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel66)
                    .addComponent(Inven_ManagePrinUpsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel70)
                    .addComponent(Inven_ManagePrinSupNameCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel71)
                    .addComponent(Inven_ManagePriBranNameCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Inven_ManagePrinterAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        Inven_ManageLapSerialTxt.addTab("Printer", jPanel34);

        jLabel10.setText("Serial Number");

        jLabel67.setText("Name");

        jLabel72.setText("Brand");

        jLabel73.setText("Model");

        jLabel74.setText("Processor");

        jLabel75.setText("RAM");

        jLabel76.setText("Hard Disk");

        Inven_ManageLapBrandTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inven_ManageLapBrandTxtActionPerformed(evt);
            }
        });

        Inven_ManageLapAddBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Save.png"))); // NOI18N
        Inven_ManageLapAddBtn.setText("ADD");
        Inven_ManageLapAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inven_ManageLapAddBtnActionPerformed(evt);
            }
        });

        Inven_ManageLapProceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inven_ManageLapProceTxtActionPerformed(evt);
            }
        });

        jLabel77.setText("Supplier Name");

        jLabel78.setText("Branch Name");

        jButton60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Update.png"))); // NOI18N
        jButton60.setText("Update");
        jButton60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton60ActionPerformed(evt);
            }
        });

        Inven_ManageLapSupNameCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inven_ManageLapSupNameCbxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(jPanel35);
        jPanel35.setLayout(jPanel35Layout);
        jPanel35Layout.setHorizontalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel35Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel35Layout.createSequentialGroup()
                        .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(Inven_ManageLapBrandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel35Layout.createSequentialGroup()
                        .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(Inven_ManageLapModelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel35Layout.createSequentialGroup()
                        .addComponent(jLabel74, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(Inven_ManageLapProceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel35Layout.createSequentialGroup()
                        .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(Inven_ManageLapRamTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel35Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(Inven_ManageLapAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton60))
                    .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel35Layout.createSequentialGroup()
                            .addComponent(jLabel76, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(35, 35, 35)
                            .addComponent(Inven_ManageLapHardTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel35Layout.createSequentialGroup()
                            .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(35, 35, 35)
                            .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Inven_ManageLapBranNameCbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Inven_ManageLapSupNameCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel35Layout.createSequentialGroup()
                        .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Inven_ManageLapNameTxt)
                            .addComponent(Inven_ManageLapSerialNoCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(477, Short.MAX_VALUE))
        );
        jPanel35Layout.setVerticalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel35Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Inven_ManageLapSerialNoCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel35Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel67))
                    .addComponent(Inven_ManageLapNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel35Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel72))
                    .addComponent(Inven_ManageLapBrandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel35Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel73))
                    .addComponent(Inven_ManageLapModelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel35Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel74))
                    .addComponent(Inven_ManageLapProceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel35Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel75))
                    .addComponent(Inven_ManageLapRamTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel35Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel76))
                    .addComponent(Inven_ManageLapHardTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel77)
                    .addComponent(Inven_ManageLapSupNameCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel78)
                    .addComponent(Inven_ManageLapBranNameCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Inven_ManageLapAddBtn)
                    .addComponent(jButton60))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        Inven_ManageLapSerialTxt.addTab("Laptops", jPanel35);

        jLabel81.setText("Model");

        Inven_ManageOtherBrandTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inven_ManageOtherBrandTxtActionPerformed(evt);
            }
        });

        jButton61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Update.png"))); // NOI18N
        jButton61.setText("Update");
        jButton61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton61ActionPerformed(evt);
            }
        });

        jButton35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Save.png"))); // NOI18N
        jButton35.setText("Add");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });

        jLabel83.setText("Branch Name");

        jLabel82.setText("Supplier Name");

        jLabel79.setText("Name");

        jLabel80.setText("Brand");

        jLabel11.setText("Serial Number");

        Inven_ManageOthSupNameCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inven_ManageOthSupNameCbxActionPerformed(evt);
            }
        });

        Inven_ManageOthBranNameCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inven_ManageOthBranNameCbxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
        jPanel37.setLayout(jPanel37Layout);
        jPanel37Layout.setHorizontalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel37Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel37Layout.createSequentialGroup()
                        .addComponent(jLabel80, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(Inven_ManageOtherBrandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel37Layout.createSequentialGroup()
                        .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(Inven_ManageOtherModelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel37Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButton61))
                    .addGroup(jPanel37Layout.createSequentialGroup()
                        .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel82, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel83, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Inven_ManageOthBranNameCbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Inven_ManageOthSupNameCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel37Layout.createSequentialGroup()
                        .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Inven_ManageOtherNameTxt)
                            .addComponent(Inven_ManageOtherSerialNoCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(476, Short.MAX_VALUE))
        );
        jPanel37Layout.setVerticalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel37Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Inven_ManageOtherSerialNoCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel37Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel79))
                    .addComponent(Inven_ManageOtherNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel37Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel80))
                    .addComponent(Inven_ManageOtherBrandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel37Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel81))
                    .addComponent(Inven_ManageOtherModelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel82)
                    .addComponent(Inven_ManageOthSupNameCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel83)
                    .addComponent(Inven_ManageOthBranNameCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton61, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        Inven_ManageLapSerialTxt.addTab("Other", jPanel37);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Inven_ManageLapSerialTxt)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Inven_ManageLapSerialTxt, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane3.addTab("Manage Items", new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/On Screen Keyboard.png")), jPanel8); // NOI18N

        jPanel39.setMinimumSize(new java.awt.Dimension(740, 479));
        jPanel39.setPreferredSize(new java.awt.Dimension(740, 479));

        jButton36.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton36.setText("View Summery");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });

        Inven_ReportTypeCbx.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Inven_ReportTypeCbx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PC", "LAPTOP", "PRINTER", "CPU" }));
        Inven_ReportTypeCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inven_ReportTypeCbxActionPerformed(evt);
            }
        });

        jLabel84.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel84.setText("Type");

        javax.swing.GroupLayout jPanel39Layout = new javax.swing.GroupLayout(jPanel39);
        jPanel39.setLayout(jPanel39Layout);
        jPanel39Layout.setHorizontalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel39Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel84, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(Inven_ReportTypeCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jButton36, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel39Layout.setVerticalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel39Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel84, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Inven_ReportTypeCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton36, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(412, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("View Reports", new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Task Manager alt 2.png")), jPanel39); // NOI18N

        jPanel40.setPreferredSize(new java.awt.Dimension(740, 247));

        jLabel85.setText("Serial Number");

        jLabel7.setText("User name");

        jLabel86.setText("Position");

        jButton37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Save.png"))); // NOI18N
        jButton37.setText("Assign");
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });

        jLabel123.setText("Type");

        Inven_AssgnUsrSerialNoCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inven_AssgnUsrSerialNoCbxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel40Layout = new javax.swing.GroupLayout(jPanel40);
        jPanel40.setLayout(jPanel40Layout);
        jPanel40Layout.setHorizontalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel40Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel40Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(user_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel40Layout.createSequentialGroup()
                        .addComponent(jLabel86, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(position_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel40Layout.createSequentialGroup()
                        .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel123, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel85, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Inven_AssgnUsrSerialNoCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(type_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(491, Short.MAX_VALUE))
        );
        jPanel40Layout.setVerticalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel40Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel85)
                    .addComponent(Inven_AssgnUsrSerialNoCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel123)
                    .addComponent(type_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel40Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7))
                    .addComponent(user_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel40Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel86))
                    .addComponent(position_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Assign User", new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/User Accounts alt.png")), jPanel40); // NOI18N

        jLabel87.setText("Serial Number");

        jLabel88.setText("Parts");

        jCheckBox1.setText("Printer");

        jCheckBox2.setText("Mouse");

        jCheckBox3.setText("CPU");

        jCheckBox4.setText("UPS");

        jButton38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Save.png"))); // NOI18N
        jButton38.setText("Assign Parts");
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });

        jLabel124.setText("Type");

        jLabel125.setText("Serial Number");

        javax.swing.GroupLayout jPanel41Layout = new javax.swing.GroupLayout(jPanel41);
        jPanel41.setLayout(jPanel41Layout);
        jPanel41Layout.setHorizontalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel41Layout.createSequentialGroup()
                .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel41Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel87)
                        .addGap(36, 36, 36)
                        .addComponent(Inven_AssgnPartSerialNoCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel41Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel124, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jTextField65, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel41Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel125)
                        .addGap(35, 35, 35)
                        .addComponent(jTextField89, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel41Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel88, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jCheckBox2)
                        .addGap(0, 0, 0)
                        .addComponent(jCheckBox3)
                        .addGap(4, 4, 4)
                        .addComponent(jCheckBox1)
                        .addGap(2, 2, 2)
                        .addComponent(jCheckBox4))
                    .addGroup(jPanel41Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(478, 478, 478))
        );
        jPanel41Layout.setVerticalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel41Layout.createSequentialGroup()
                .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel41Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel87))
                    .addGroup(jPanel41Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(Inven_AssgnPartSerialNoCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel41Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel124))
                    .addComponent(jTextField65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel41Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel125))
                    .addComponent(jTextField89, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel41Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel88))
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox4))
                .addGap(18, 18, 18)
                .addComponent(jButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Assign Parts", new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/On Screen Keyboard.png")), jPanel41); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Inven_InvenDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inven_InvenDeleteBtnActionPerformed
        // TODO add your handling code here:

        if (JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this item?", "", 0) != 0) {
            return;
        }
        HelperInventory.deleteInventoryItem(this);
    }//GEN-LAST:event_Inven_InvenDeleteBtnActionPerformed

    private void Inven_ManagePcBrandTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inven_ManagePcBrandTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Inven_ManagePcBrandTxtActionPerformed

    private void Inven_ManagePcAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inven_ManagePcAddBtnActionPerformed
        HelperInventory.addPCToInventory(this);
    }//GEN-LAST:event_Inven_ManagePcAddBtnActionPerformed

    private void Inven_ManagePcProceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inven_ManagePcProceTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Inven_ManagePcProceTxtActionPerformed

    private void Inven_ManagePcUpdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inven_ManagePcUpdBtnActionPerformed
        // TODO add your handling code here:
        HelperInventory.UpdateInventoryPC(this);
    }//GEN-LAST:event_Inven_ManagePcUpdBtnActionPerformed

    private void Inven_ManagePrinterAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inven_ManagePrinterAddBtnActionPerformed
        HelperInventory.addPrinterToInventory(this);
    }//GEN-LAST:event_Inven_ManagePrinterAddBtnActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        HelperInventory.UpdateInventoryPrinter(this);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void Inven_ManageLapBrandTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inven_ManageLapBrandTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Inven_ManageLapBrandTxtActionPerformed

    private void Inven_ManageLapAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inven_ManageLapAddBtnActionPerformed
        HelperInventory.addLaptopToInventory(this);
    }//GEN-LAST:event_Inven_ManageLapAddBtnActionPerformed

    private void Inven_ManageLapProceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inven_ManageLapProceTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Inven_ManageLapProceTxtActionPerformed

    private void Inven_ManageLapSupNameCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inven_ManageLapSupNameCbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Inven_ManageLapSupNameCbxActionPerformed

    private void Inven_ManageOtherBrandTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inven_ManageOtherBrandTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Inven_ManageOtherBrandTxtActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        String serialNo = ComboItem.getValue(Inven_ManageOtherSerialNoCbx.getSelectedItem());
        String type = Inven_ManageOtherNameTxt.getText();
        String name = Inven_ManageOtherBrandTxt.getText();
        String brand = Inven_ManageOtherBrandTxt.getText();
        String model = Inven_ManageOtherModelTxt.getText();
        String supplier = ComboItem.getValue(Inven_ManagePcSupNameCbx.getSelectedItem());//Inven_ManagePcSupNameTxt.getText();
        String branch = ComboItem.getValue(Inven_ManagePcBranNameCbx.getSelectedItem());
        String ram = null;
        String processor = null;
        String hard = null;
        String printer_type = null;
        String front = null;
        String ups = null;

        Inventory inven = new Inventory();
        String it = inven.addInventory(serialNo, name, type, brand, model, supplier, branch, ram, processor, hard, printer_type, front, ups);
        System.err.println(it);
    }//GEN-LAST:event_jButton35ActionPerformed

    private void Inven_ManageOthSupNameCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inven_ManageOthSupNameCbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Inven_ManageOthSupNameCbxActionPerformed

    private void Inven_ManageOthBranNameCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inven_ManageOthBranNameCbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Inven_ManageOthBranNameCbxActionPerformed

    private void Inven_ReportTypeCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inven_ReportTypeCbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Inven_ReportTypeCbxActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        // TODO add your handling code here:
        HelperInventory.addUser(this);
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        // TODO add your handling code here:

        String type = Inven_ReportTypeCbx.getSelectedItem().toString();

        ReportViewer viewr = new ReportViewer();
        HashMap hmp = new HashMap();
        hmp.put("my_query", type);
        viewr.showReport("InventoryReport.jrxml", hmp);
    }//GEN-LAST:event_jButton36ActionPerformed

    private void Inven_InvenUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inven_InvenUpdateBtnActionPerformed
        // TODO add your handling code here:
        jTabbedPane3.setSelectedIndex(1);
    }//GEN-LAST:event_Inven_InvenUpdateBtnActionPerformed

    private void jButton60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton60ActionPerformed
        // TODO add your handling code here:
        HelperInventory.UpdateInventoryPC(this);
    }//GEN-LAST:event_jButton60ActionPerformed

    private void jButton61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton61ActionPerformed
        // TODO add your handling code here:
        HelperInventory.UpdateInventoryOther(this);
    }//GEN-LAST:event_jButton61ActionPerformed

    private void Inven_AssgnUsrSerialNoCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inven_AssgnUsrSerialNoCbxActionPerformed
        String SerialNo = ComboItem.getValue(Inven_AssgnUsrSerialNoCbx.getSelectedItem());
        if (SerialNo.equals("")) {
            JOptionPane.showMessageDialog(this, "Please select product serial No");
        } else {
            HelperInventory.getInventoryDetails(this);
        }

    }//GEN-LAST:event_Inven_AssgnUsrSerialNoCbxActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox Inven_AssgnPartSerialNoCbx;
    public javax.swing.JComboBox Inven_AssgnUsrSerialNoCbx;
    public javax.swing.JButton Inven_InvenDeleteBtn;
    public javax.swing.JTable Inven_InvenTlbl;
    public javax.swing.JButton Inven_InvenUpdateBtn;
    public javax.swing.JButton Inven_ManageLapAddBtn;
    public javax.swing.JComboBox Inven_ManageLapBranNameCbx;
    public javax.swing.JTextField Inven_ManageLapBrandTxt;
    public javax.swing.JTextField Inven_ManageLapHardTxt;
    public javax.swing.JTextField Inven_ManageLapModelTxt;
    public javax.swing.JTextField Inven_ManageLapNameTxt;
    public javax.swing.JTextField Inven_ManageLapProceTxt;
    public javax.swing.JTextField Inven_ManageLapRamTxt;
    public javax.swing.JComboBox Inven_ManageLapSerialNoCbx;
    public javax.swing.JTabbedPane Inven_ManageLapSerialTxt;
    public javax.swing.JComboBox Inven_ManageLapSupNameCbx;
    public javax.swing.JComboBox Inven_ManageOthBranNameCbx;
    public javax.swing.JComboBox Inven_ManageOthSupNameCbx;
    public javax.swing.JTextField Inven_ManageOtherBrandTxt;
    public javax.swing.JTextField Inven_ManageOtherModelTxt;
    public javax.swing.JTextField Inven_ManageOtherNameTxt;
    public javax.swing.JComboBox Inven_ManageOtherSerialNoCbx;
    public javax.swing.JComboBox Inven_ManagePCSerialNoCbx;
    public javax.swing.JButton Inven_ManagePcAddBtn;
    public javax.swing.JComboBox Inven_ManagePcBranNameCbx;
    public javax.swing.JTextField Inven_ManagePcBrandTxt;
    public javax.swing.JTextField Inven_ManagePcHardTxt;
    public javax.swing.JTextField Inven_ManagePcModelTxt;
    public javax.swing.JTextField Inven_ManagePcNameTxt;
    public javax.swing.JTextField Inven_ManagePcProceTxt;
    public javax.swing.JTextField Inven_ManagePcRamTxt;
    public javax.swing.JComboBox Inven_ManagePcSupNameCbx;
    public javax.swing.JButton Inven_ManagePcUpdBtn;
    public javax.swing.JComboBox Inven_ManagePriBranNameCbx;
    public javax.swing.JTextField Inven_ManagePrinBrandTxt;
    public javax.swing.JComboBox Inven_ManagePrinFrontCbx;
    public javax.swing.JTextField Inven_ManagePrinModelTxt;
    public javax.swing.JTextField Inven_ManagePrinNameTxt;
    public javax.swing.JComboBox Inven_ManagePrinSerialNoCbx;
    public javax.swing.JComboBox Inven_ManagePrinSupNameCbx;
    public javax.swing.JComboBox Inven_ManagePrinTypeCbx;
    public javax.swing.JTextField Inven_ManagePrinUpsTxt;
    public javax.swing.JButton Inven_ManagePrinterAddBtn;
    public javax.swing.JComboBox Inven_ReportTypeCbx;
    public javax.swing.JButton jButton17;
    public javax.swing.JButton jButton35;
    public javax.swing.JButton jButton36;
    public javax.swing.JButton jButton37;
    public javax.swing.JButton jButton38;
    public javax.swing.JButton jButton60;
    public javax.swing.JButton jButton61;
    public javax.swing.JCheckBox jCheckBox1;
    public javax.swing.JCheckBox jCheckBox2;
    public javax.swing.JCheckBox jCheckBox3;
    public javax.swing.JCheckBox jCheckBox4;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel123;
    public javax.swing.JLabel jLabel124;
    public javax.swing.JLabel jLabel125;
    public javax.swing.JLabel jLabel32;
    public javax.swing.JLabel jLabel42;
    public javax.swing.JLabel jLabel43;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel58;
    public javax.swing.JLabel jLabel59;
    public javax.swing.JLabel jLabel60;
    public javax.swing.JLabel jLabel61;
    public javax.swing.JLabel jLabel62;
    public javax.swing.JLabel jLabel63;
    public javax.swing.JLabel jLabel64;
    public javax.swing.JLabel jLabel65;
    public javax.swing.JLabel jLabel66;
    public javax.swing.JLabel jLabel67;
    public javax.swing.JLabel jLabel68;
    public javax.swing.JLabel jLabel69;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel70;
    public javax.swing.JLabel jLabel71;
    public javax.swing.JLabel jLabel72;
    public javax.swing.JLabel jLabel73;
    public javax.swing.JLabel jLabel74;
    public javax.swing.JLabel jLabel75;
    public javax.swing.JLabel jLabel76;
    public javax.swing.JLabel jLabel77;
    public javax.swing.JLabel jLabel78;
    public javax.swing.JLabel jLabel79;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel80;
    public javax.swing.JLabel jLabel81;
    public javax.swing.JLabel jLabel82;
    public javax.swing.JLabel jLabel83;
    public javax.swing.JLabel jLabel84;
    public javax.swing.JLabel jLabel85;
    public javax.swing.JLabel jLabel86;
    public javax.swing.JLabel jLabel87;
    public javax.swing.JLabel jLabel88;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel17;
    public javax.swing.JPanel jPanel34;
    public javax.swing.JPanel jPanel35;
    public javax.swing.JPanel jPanel37;
    public javax.swing.JPanel jPanel39;
    public javax.swing.JPanel jPanel40;
    public javax.swing.JPanel jPanel41;
    public javax.swing.JPanel jPanel8;
    public javax.swing.JPanel jPanel9;
    public javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTabbedPane jTabbedPane3;
    public javax.swing.JTextField jTextField65;
    public javax.swing.JTextField jTextField89;
    public javax.swing.JTextField position_txt;
    public javax.swing.JTextField type_txt;
    public javax.swing.JTextField user_txt;
    // End of variables declaration//GEN-END:variables
}
