/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package OrganizedIn.UI;

import OrganizedIn.Lib.Announcements;
import OrganizedIn.Lib.Manuals;
import OrganizedIn.Lib.SearchKnowledgeBase;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Luthasha
 */
public class Knowladge extends javax.swing.JPanel {
    
    Vector<Vector<String>> data=null;
    Vector<String> header=null;

    Announcements an = new Announcements();
    Manuals man = new Manuals();
    /**
     * Creates new form Knowladge
     */
    public Knowladge() {
        initComponents();
        
        fillItemNames() ;
        fillBrandNames();
        fillModelNames();
        
        header=new Vector<>();
        header.add("itemName");
        header.add("brand");
        header.add("model");
        header.add("ManualName");
        
    }

    
    
     private void fillItemNames(){
     
         SearchKnowledgeBase skb = new SearchKnowledgeBase();
         ArrayList ItemNameList = skb.getItemName();
          Iterator i = ItemNameList.iterator();

        while (i.hasNext()) {
            cbo_itmName.addItem(i.next());
        }

        String ItemName = cbo_itmName.getSelectedItem().toString();

    
}
      private void fillBrandNames(){
     
         SearchKnowledgeBase skb1 = new SearchKnowledgeBase();
         ArrayList BrandNameList = skb1.getBrandName();
          Iterator i = BrandNameList.iterator();

        while (i.hasNext()) {
            cbo_brandName.addItem(i.next());
        }

        String brandName = cbo_brandName.getSelectedItem().toString();

    
}
    private void fillModelNames(){
     
         SearchKnowledgeBase skb2 = new SearchKnowledgeBase();
         ArrayList ModelNameList = skb2.getModelName();
          Iterator i = ModelNameList.iterator();

        while (i.hasNext()) {
            cbo_model.addItem(i.next());
        }

        String modelName = cbo_model.getSelectedItem().toString();

    
}  
    
private void selectRow() {
//retrieving the selected row index
int row = tbl_announcements.getSelectedRow();
//if a single row is selected from the table, take each cell values into the controls
if (tbl_announcements.getRowSelectionAllowed()) {

txt_announcementFull.setText(tbl_announcements.getValueAt(row, 2).toString());

}
}
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_manualId = new javax.swing.JTextField();
        txt_itemName = new javax.swing.JTextField();
        txt_filePath = new javax.swing.JTextField();
        btn_manualadd = new javax.swing.JButton();
        btn_manualupdate = new javax.swing.JButton();
        btn_manualdelete = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        cbo_brand = new javax.swing.JComboBox();
        btn_manualsearch = new javax.swing.JButton();
        btn_manualclear = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txt_model = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_manualname = new javax.swing.JTextField();
        txt_date = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_manuals = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        cbo_itmName = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cbo_brandName = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        cbo_model = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        MainCardAnnouncementsjPanel11 = new javax.swing.JPanel();
        ListAnnouncements = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txt_searchAnn = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_announcements = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txt_announcementFull = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_announcementId = new javax.swing.JTextField();
        txt_subject = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        txt_Date = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_announcement = new javax.swing.JTextArea();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_targetGroup = new javax.swing.JTextArea();

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Manual ID");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Item Name");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("File Path");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Date Modified");

        txt_manualId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txt_itemName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_itemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_itemNameActionPerformed(evt);
            }
        });

        txt_filePath.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_filePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_filePathActionPerformed(evt);
            }
        });

        btn_manualadd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_manualadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Save.png"))); // NOI18N
        btn_manualadd.setText("Add");
        btn_manualadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manualaddActionPerformed(evt);
            }
        });

        btn_manualupdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_manualupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Update.png"))); // NOI18N
        btn_manualupdate.setText("Update");
        btn_manualupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manualupdateActionPerformed(evt);
            }
        });

        btn_manualdelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_manualdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Recycle Bin Full.png"))); // NOI18N
        btn_manualdelete.setText("Delete");
        btn_manualdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manualdeleteActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Manage Manuals");

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel35.setText("Brand");

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel36.setText("Model");

        cbo_brand.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbo_brand.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Acer", "ABS", "Apple", "Asus", "Dell" }));

        btn_manualsearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_manualsearch.setText("Search");
        btn_manualsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manualsearchActionPerformed(evt);
            }
        });

        btn_manualclear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_manualclear.setText("Clear");
        btn_manualclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manualclearActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Select");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Manual Name");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel36)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_manualId, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(txt_itemName)
                            .addComponent(txt_filePath)
                            .addComponent(cbo_brand, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_model)
                            .addComponent(txt_manualname)
                            .addComponent(txt_date))
                        .addGap(29, 29, 29)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(btn_manualadd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_manualupdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_manualdelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_manualsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_manualclear)))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel11)
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_manualId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_itemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(cbo_brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(txt_model, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_manualname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_filePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel9)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_manualadd)
                    .addComponent(btn_manualupdate)
                    .addComponent(btn_manualdelete)
                    .addComponent(btn_manualsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_manualclear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(169, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(" Manuals", new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x32/Internet Options.png")), jPanel3); // NOI18N

        jTabbedPane3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Search Manuals");

        tbl_manuals.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_manuals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Item Name", "Brand", "Model", "Manual"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbl_manuals);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Advanced Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        cbo_itmName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbo_itmName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NULL" }));
        cbo_itmName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_itmNameActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Item");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Brand");

        cbo_brandName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbo_brandName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NULL" }));
        cbo_brandName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_brandNameActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("Model");

        cbo_model.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbo_model.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NULL" }));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel22)
                        .addComponent(jLabel23)))
                .addGap(91, 91, 91)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbo_itmName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbo_brandName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbo_model, 0, 165, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbo_itmName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel23))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbo_brandName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel24))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cbo_model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Manuals", new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Internet Options.png")), jPanel10); // NOI18N

        MainCardAnnouncementsjPanel11.setLayout(new java.awt.CardLayout());

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Search Announcments");

        txt_searchAnn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_searchAnn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchAnnKeyReleased(evt);
            }
        });

        tbl_announcements.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_announcements.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Subject", "Target Group", "Announcement"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_announcements.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_announcementsMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbl_announcements);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Search ");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txt_announcementFull.setColumns(20);
        txt_announcementFull.setRows(5);
        jScrollPane6.setViewportView(txt_announcementFull);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Announcement");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ListAnnouncementsLayout = new javax.swing.GroupLayout(ListAnnouncements);
        ListAnnouncements.setLayout(ListAnnouncementsLayout);
        ListAnnouncementsLayout.setHorizontalGroup(
            ListAnnouncementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListAnnouncementsLayout.createSequentialGroup()
                .addGroup(ListAnnouncementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ListAnnouncementsLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(ListAnnouncementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListAnnouncementsLayout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(133, 133, 133))))
                    .addGroup(ListAnnouncementsLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(ListAnnouncementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(txt_searchAnn, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        ListAnnouncementsLayout.setVerticalGroup(
            ListAnnouncementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListAnnouncementsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGap(31, 31, 31)
                .addGroup(ListAnnouncementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_searchAnn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MainCardAnnouncementsjPanel11.add(ListAnnouncements, "card2");

        jTabbedPane3.addTab("Announcements", new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Contacts.png")), MainCardAnnouncementsjPanel11); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );

        jTabbedPane1.addTab("Search Knowledge Base", new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x32/Indexing Options.png")), jPanel1); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Announcement ID");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Subject");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Target Group");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Announcement");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Date");

        txt_announcementId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txt_subject.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_subjectActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Manage Announcements");

        btn_add.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Save.png"))); // NOI18N
        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_update.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Update.png"))); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Recycle Bin Full.png"))); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        txt_Date.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txt_announcement.setColumns(20);
        txt_announcement.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_announcement.setRows(5);
        jScrollPane1.setViewportView(txt_announcement);

        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton8.setText("Search");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton7.setText("Clear");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        txt_targetGroup.setColumns(20);
        txt_targetGroup.setRows(5);
        jScrollPane2.setViewportView(txt_targetGroup);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 242, Short.MAX_VALUE)
                        .addComponent(btn_add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addGap(53, 53, 53)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_subject, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_announcementId, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_Date, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGap(0, 125, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel17)
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_announcementId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(86, 86, 86)
                        .addComponent(jLabel16))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(81, 81, 81)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add)
                    .addComponent(btn_update)
                    .addComponent(btn_delete)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Announcements", new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x32/Contacts.png")), jPanel4); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_itemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_itemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_itemNameActionPerformed

    private void txt_filePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_filePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_filePathActionPerformed

    private void btn_manualupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manualupdateActionPerformed
        String manualId = txt_manualId.getText();
        String itemName = txt_itemName.getText();
        String brand = cbo_brand.getSelectedItem().toString();
        String model = txt_model.getText();
        String manualName = txt_manualname.getText();
        String filePath = txt_filePath.getText();
        String modDate = txt_date.getText();
        
        man.updateManual(manualId, itemName, brand, model, manualName, filePath, modDate);
    }//GEN-LAST:event_btn_manualupdateActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
       
        String announcementId  = txt_announcementId.getText();
        String subject = txt_subject.getText();
        String targetGroup = txt_targetGroup.getText();
        String announcement = txt_announcement.getText();
        String modDate = txt_Date.getText();
       
       /* SimpleDateFormat sm = new SimpleDateFormat("yyyy-MM-dd");
        String jDate = "";
        try {
            jDate = sm.format(joinedDatePicker.getDate());
        } catch (Exception e) {
            System.out.println("date failed");
        }

        String modifyDate = joinedDatePicker.getDateFormatString();*/

        
        
          boolean add = an.addAnnouncement(announcementId, subject, targetGroup, announcement, modDate);
       
        

    }//GEN-LAST:event_btn_addActionPerformed

    private void txt_subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_subjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_subjectActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        
        String announcementId = txt_announcementId.getText();
        
        boolean delete = an.deleteAnnouncement(announcementId);
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
      
        String announcementId  = txt_announcementId.getText();
        String subject = txt_subject.getText();
        String targetGroup = txt_targetGroup.getText();
        String announcement = txt_announcement.getText();
        String modDate = txt_Date.getText();
        
        an.updateAnnouncement(announcementId, subject, targetGroup, announcement, modDate);
        
    }//GEN-LAST:event_btn_updateActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
         
        String announcementId = txt_announcementId.getText();
        String[] Array1 = new String[4];
        an.searchAnnouncement(announcementId, Array1);
        
        String subject = Array1[0];
        String targetGrp = Array1[1];
        String announcement = Array1[2];
        String date = Array1[3];
        
        txt_subject.setText(subject);
        txt_targetGroup.setText(targetGrp);
        txt_announcement.setText(announcement);
        txt_Date.setText(date);
                
        
        
        
        
        
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
//txt_announcementId.setText("");
txt_subject.setText("");
txt_targetGroup.setText("");
txt_announcement.setText("");
txt_Date.setText("");

        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btn_manualaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manualaddActionPerformed
        String manualId   = txt_manualId.getText();
        String itemName = txt_itemName.getText();
        String brand = cbo_brand.getSelectedItem().toString();
        String model = txt_model.getText();
        String manualName = txt_manualname.getText();
        String filePath = txt_filePath.getText();
       String modDate = txt_date.getText();
        
        
        man.addManual(manualId, itemName, brand, model, manualName, filePath, modDate);
        
       
        
    }//GEN-LAST:event_btn_manualaddActionPerformed

    private void btn_manualdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manualdeleteActionPerformed
        String manuId = txt_manualId.getText();
        
        man.deleteManual(manuId);
    }//GEN-LAST:event_btn_manualdeleteActionPerformed

    private void btn_manualsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manualsearchActionPerformed
        String manualId = txt_manualId.getText();
        String[] Array1 = new String[6];
        man.searchManual(manualId, Array1);
        
        String itemName = Array1[0];
        String brand = Array1[1];
        String model = Array1[2];
        String manualName = Array1[3];
        String filePath = Array1[4];
        String date = Array1[5];
        
        
        txt_itemName.setText(itemName);
        cbo_brand.setSelectedItem(brand);
        txt_model.setText(model);
        txt_manualname.setText(manualName);
        txt_filePath.setText(filePath);
        txt_date.setText(date);
    }//GEN-LAST:event_btn_manualsearchActionPerformed

    private void btn_manualclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manualclearActionPerformed
//txt_manualId.setText("");
txt_itemName.setText("");
txt_model.setText("");
txt_manualname.setText("");
txt_filePath.setText("");
txt_date.setText("");

    }//GEN-LAST:event_btn_manualclearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        manualName=f.getAbsolutePath();
        txt_filePath.setText(manualName);

        try
        {
            File addManu=new File(manualName);
            FileInputStream fis=new FileInputStream(addManu);
            ByteArrayOutputStream bos=new ByteArrayOutputStream();
            byte[] buff=new byte[1024];

            for(int readNum;(readNum=fis.read(buff)) != -1;)
            {
                bos.write(buff,0,readNum);
            }

             addManual=bos.toByteArray();

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
                         

    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbo_itmNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_itmNameActionPerformed
    





     
     
        
    }//GEN-LAST:event_cbo_itmNameActionPerformed

    private void txt_searchAnnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchAnnKeyReleased
        
        String value = txt_searchAnn.getText();
        SearchKnowledgeBase skb3 = new SearchKnowledgeBase();
        
        try{
            ResultSet rst = skb3.getAnnouncementsBytyping(value);
            
            DefaultTableModel dtm = (DefaultTableModel)tbl_announcements.getModel();
            
            dtm.setRowCount(0);
            dtm.setColumnCount(0);
            
            dtm.addColumn("Subject");
            dtm.addColumn("targetGroup");
            dtm.addColumn("Announcement");
            
            
            
            while(rst.next()){
                Vector v = new Vector();
                v.add(rst.getString(1));
                v.add(rst.getString(2));
                v.add(rst.getString(3));
                
                dtm.addRow(v);
            }
        }catch(Exception e){
            System.out.println("Loading table by typing "+e);
        }
        
        
                                    
    }//GEN-LAST:event_txt_searchAnnKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String item=cbo_itmName.getSelectedItem().toString();
        String brand=cbo_brand.getSelectedItem().toString();
        String model=cbo_model.getSelectedItem().toString();
       
        Manuals m=new Manuals(item, brand, model);
        SearchKnowledgeBase skb4 = new SearchKnowledgeBase();
        data=skb4.searchManuals(m);
        tbl_manuals.setModel(new DefaultTableModel(data,header));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbo_brandNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_brandNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_brandNameActionPerformed

    private void tbl_announcementsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_announcementsMouseClicked
        selectRow();
    }//GEN-LAST:event_tbl_announcementsMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ListAnnouncements;
    private javax.swing.JPanel MainCardAnnouncementsjPanel11;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_manualadd;
    private javax.swing.JButton btn_manualclear;
    private javax.swing.JButton btn_manualdelete;
    private javax.swing.JButton btn_manualsearch;
    private javax.swing.JButton btn_manualupdate;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox cbo_brand;
    private javax.swing.JComboBox cbo_brandName;
    private javax.swing.JComboBox cbo_itmName;
    private javax.swing.JComboBox cbo_model;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable tbl_announcements;
    private javax.swing.JTable tbl_manuals;
    private javax.swing.JTextField txt_Date;
    private javax.swing.JTextArea txt_announcement;
    private javax.swing.JTextArea txt_announcementFull;
    private javax.swing.JTextField txt_announcementId;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_filePath;
    private javax.swing.JTextField txt_itemName;
    private javax.swing.JTextField txt_manualId;
    private javax.swing.JTextField txt_manualname;
    private javax.swing.JTextField txt_model;
    private javax.swing.JTextField txt_searchAnn;
    private javax.swing.JTextField txt_subject;
    private javax.swing.JTextArea txt_targetGroup;
    // End of variables declaration//GEN-END:variables

    String manualName=null;
    int s=0;
    byte[] addManual=null;

}



