/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package OrganizedIn.UI;

import OrganizedIn.Lib.OrgSystem;
import OrganizedIn.Lib.User;
import javax.swing.JOptionPane;

/**
 *
 * @author gamunu
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Login_UsernameTxt = new javax.swing.JTextField();
        Login_PasswordTxt = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Login_LoginBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(493, 324));
        setPreferredSize(new java.awt.Dimension(513, 383));
        setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(493, 363));
        jPanel1.setPreferredSize(new java.awt.Dimension(513, 383));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x32/leco_logo32.png"))); // NOI18N
        jLabel2.setToolTipText("");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        Login_UsernameTxt.setFont(OrgSystem.getFont()); // NOI18N

        Login_PasswordTxt.setFont(OrgSystem.getFont()); // NOI18N

        jLabel1.setFont(OrgSystem.getFont()); // NOI18N
        jLabel1.setText("Username");

        jLabel3.setFont(OrgSystem.getFont()); // NOI18N
        jLabel3.setText("Password");

        Login_LoginBtn.setFont(OrgSystem.getFont()); // NOI18N
        Login_LoginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x32/Power - Standby.png"))); // NOI18N
        Login_LoginBtn.setText("Login");
        Login_LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_LoginBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Login_LoginBtn)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Login_UsernameTxt)
                                    .addComponent(Login_PasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Login_UsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Login_PasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(Login_LoginBtn)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Login_LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_LoginBtnActionPerformed
        if (Login_UsernameTxt != null && Login_PasswordTxt != null) {

            if (User.isValidUser(Login_UsernameTxt.getText(), Login_PasswordTxt.getText())) {

                //Set user system wide. important
                User.setSystemUser(Login_UsernameTxt.getText());

                if (OrgSystem.User.hasPrivilege("can:login")) {
                    MainInterface mn = new MainInterface();
                    mn.setVisible(true);
                    System.out.println("valid user!!");
                    this.dispose();
                    this.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, "You don't have permission to login to this system", "Hello", 2);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Check username or password", "Hello", 2);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Enter username or password", "Hello", 1);
        }
    }//GEN-LAST:event_Login_LoginBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login_LoginBtn;
    private javax.swing.JPasswordField Login_PasswordTxt;
    private javax.swing.JTextField Login_UsernameTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
