/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package OrganizedIn.UI;

import OrganizedIn.Lib.Helper.HelperPayments;
import OrganizedIn.Lib.OrgSystem;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mayuri
 */
public class PaymentsPanel extends javax.swing.JPanel {
        HelperPayments hp = new HelperPayments();
    /**
     * Creates new form PaymentsPanel
     */
    public PaymentsPanel() {
        initComponents();
        loadInvoiceNum();
        loadRecieptNum();
        
        
    }
    public void loadInvoiceNum() {
        
   /*     DefaultComboBoxModel cbx = new DefaultComboBoxModel();
        try {
            HelperPayments hp = new HelperPayments();
            ArrayList invoicenumList = hp.getInvoiceNum(); ;

            Iterator i = invoicenumList.iterator();

            while (i.hasNext()) {

                cbx.addElement(i.next());
            }
        } catch (Exception ex) {
        }

        invoicenum.setModel(cbx);*/
    }
    
    public void  loadRecieptNum(){
  /*      DefaultComboBoxModel cbx = new DefaultComboBoxModel();
        try {
            HelperPayments hp = new HelperPayments();
            ArrayList RecieptNum = hp.getReceiptNum();

            Iterator i = RecieptNum.iterator();

            while (i.hasNext()) {

                cbx.addElement(i.next());
            }
        } catch (Exception ex) {
        }

        recieptnum.setModel(cbx);*/
    }
    
    
    public void loadTable(){
        HelperPayments hp = new HelperPayments();
    try{
            ResultSet rst = hp.grnRecords();
            
            DefaultTableModel dtm = (DefaultTableModel)grntbl.getModel();
            
            dtm.setRowCount(0);
            dtm.setColumnCount(0);
            
            dtm.addColumn("");
            dtm.addColumn("");
            dtm.addColumn("");
            dtm.addColumn("");
            
            while(rst.next()){
                Vector v = new Vector();
                v.add(rst.getString("vehicle"));
                v.add(rst.getString("travel_guide"));
                v.add(rst.getString("from_date"));
                v.add(rst.getString("to_date"));
                dtm.addRow(v);
            }
            

            
        }
        catch (SQLException ex){}

    }                             

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel55 = new javax.swing.JPanel();
        jTabbedPane16 = new javax.swing.JTabbedPane();
        jPanel56 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        reciptnum = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        totamount = new javax.swing.JTextField();
        jButton60 = new javax.swing.JButton();
        jLabel124 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        date1 = new javax.swing.JTextField();
        jButton67 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        invoicenum = new javax.swing.JComboBox();
        jPanel58 = new javax.swing.JPanel();
        jTabbedPane17 = new javax.swing.JTabbedPane();
        jPanel52 = new javax.swing.JPanel();
        jLabel127 = new javax.swing.JLabel();
        orderNum = new javax.swing.JTextField();
        jLabel128 = new javax.swing.JLabel();
        supplier1 = new javax.swing.JTextField();
        jLabel129 = new javax.swing.JLabel();
        jScrollPane18 = new javax.swing.JScrollPane();
        GRNDes = new javax.swing.JTextArea();
        send = new javax.swing.JTextField();
        jLabel130 = new javax.swing.JLabel();
        jPanel54 = new javax.swing.JPanel();
        jButton65 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        receiver = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        recieptnum = new javax.swing.JComboBox();
        maincardGRNjPanel53 = new javax.swing.JPanel();
        GRNdetailsjPanel53 = new javax.swing.JPanel();
        jScrollPane20 = new javax.swing.JScrollPane();
        grntbl = new javax.swing.JTable();
        jButton17 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        updateGRNjPanel53 = new javax.swing.JPanel();
        jTextField97 = new javax.swing.JTextField();
        jLabel133 = new javax.swing.JLabel();
        jLabel134 = new javax.swing.JLabel();
        jTextField98 = new javax.swing.JTextField();
        jLabel136 = new javax.swing.JLabel();
        jTextField99 = new javax.swing.JTextField();
        jButton63 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jTabbedPane18 = new javax.swing.JTabbedPane();
        maincardconfirmationjPanel49 = new javax.swing.JPanel();
        addjPanel53 = new javax.swing.JPanel();
        jLabel123 = new javax.swing.JLabel();
        jLabel135 = new javax.swing.JLabel();
        jLabel137 = new javax.swing.JLabel();
        jLabel139 = new javax.swing.JLabel();
        invoiceNum = new javax.swing.JTextField();
        PurchaseDate = new javax.swing.JTextField();
        Quantity = new javax.swing.JTextField();
        Supplier = new javax.swing.JTextField();
        jButton69 = new javax.swing.JButton();
        jLabel145 = new javax.swing.JLabel();
        Item = new javax.swing.JComboBox();
        maincardpurchsesjPanel57 = new javax.swing.JPanel();
        detailsjPanel49 = new javax.swing.JPanel();
        jScrollPane21 = new javax.swing.JScrollPane();
        jTable17 = new javax.swing.JTable();
        jButton71 = new javax.swing.JButton();
        updatejPanel53 = new javax.swing.JPanel();
        jLabel140 = new javax.swing.JLabel();
        jTextField104 = new javax.swing.JTextField();
        jLabel141 = new javax.swing.JLabel();
        jTextField105 = new javax.swing.JTextField();
        jLabel142 = new javax.swing.JLabel();
        jTextField106 = new javax.swing.JTextField();
        jLabel143 = new javax.swing.JLabel();
        jTextField107 = new javax.swing.JTextField();
        jLabel144 = new javax.swing.JLabel();
        jTextField108 = new javax.swing.JTextField();
        jButton72 = new javax.swing.JButton();
        jButton73 = new javax.swing.JButton();
        jLabel146 = new javax.swing.JLabel();
        jTextField110 = new javax.swing.JTextField();

        jTabbedPane5.setFont(OrgSystem.getFont()); // NOI18N

        jTabbedPane16.setFont(OrgSystem.getFont()); // NOI18N

        jLabel12.setFont(OrgSystem.getFont()); // NOI18N
        jLabel12.setText("Receipt Number");

        reciptnum.setFont(OrgSystem.getFont()); // NOI18N

        jLabel18.setFont(OrgSystem.getFont()); // NOI18N
        jLabel18.setText("Total Amount Paid");

        totamount.setFont(OrgSystem.getFont()); // NOI18N

        jButton60.setFont(OrgSystem.getFont()); // NOI18N
        jButton60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Windows Card Space.png"))); // NOI18N
        jButton60.setText("Add");
        jButton60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton60ActionPerformed(evt);
            }
        });

        jLabel124.setFont(OrgSystem.getFont()); // NOI18N
        jLabel124.setText("Type");

        jLabel125.setFont(OrgSystem.getFont()); // NOI18N
        jLabel125.setText("Date");

        date1.setFont(OrgSystem.getFont()); // NOI18N

        jButton67.setFont(OrgSystem.getFont()); // NOI18N
        jButton67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/System Information.png"))); // NOI18N
        jButton67.setText("View payment details");
        jButton67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton67ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cheque", "Cash" }));

        jLabel2.setText("Invoice Number List");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel125, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel124, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12))
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                                .addComponent(jButton60, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton67)
                                .addGap(146, 146, 146))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(invoicenum, 0, 250, Short.MAX_VALUE)
                                    .addComponent(reciptnum, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(totamount)
                                    .addComponent(date1)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(invoicenum, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(reciptnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(totamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel124, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel125)
                    .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton60)
                    .addComponent(jButton67))
                .addContainerGap(183, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel56Layout = new javax.swing.GroupLayout(jPanel56);
        jPanel56.setLayout(jPanel56Layout);
        jPanel56Layout.setHorizontalGroup(
            jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 844, Short.MAX_VALUE)
            .addGroup(jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel56Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel56Layout.setVerticalGroup(
            jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
            .addGroup(jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel56Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane16.addTab("Add Payments", new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/On Screen Keyboard.png")), jPanel56); // NOI18N

        jTabbedPane17.setFont(OrgSystem.getFont()); // NOI18N

        jLabel127.setFont(OrgSystem.getFont()); // NOI18N
        jLabel127.setText("Order Number");

        orderNum.setFont(OrgSystem.getFont()); // NOI18N

        jLabel128.setFont(OrgSystem.getFont()); // NOI18N
        jLabel128.setText("Supplier");

        supplier1.setFont(OrgSystem.getFont()); // NOI18N

        jLabel129.setFont(OrgSystem.getFont()); // NOI18N
        jLabel129.setText("GRN Description");

        GRNDes.setColumns(20);
        GRNDes.setFont(OrgSystem.getFont()); // NOI18N
        GRNDes.setRows(5);
        jScrollPane18.setViewportView(GRNDes);

        send.setFont(OrgSystem.getFont()); // NOI18N

        jLabel130.setFont(OrgSystem.getFont()); // NOI18N
        jLabel130.setText("Receiver");

        jPanel54.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Printing"));
        jPanel54.setFont(OrgSystem.getFont()); // NOI18N

        jButton65.setFont(OrgSystem.getFont()); // NOI18N
        jButton65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Recent Items.png"))); // NOI18N
        jButton65.setText("Add");
        jButton65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton65ActionPerformed(evt);
            }
        });

        jButton68.setFont(OrgSystem.getFont()); // NOI18N
        jButton68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Mail.png"))); // NOI18N
        jButton68.setText("Send");

        javax.swing.GroupLayout jPanel54Layout = new javax.swing.GroupLayout(jPanel54);
        jPanel54.setLayout(jPanel54Layout);
        jPanel54Layout.setHorizontalGroup(
            jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel54Layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addGroup(jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton68, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton65, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        jPanel54Layout.setVerticalGroup(
            jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel54Layout.createSequentialGroup()
                .addComponent(jButton65, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jButton68, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jLabel1.setText("Sender");

        receiver.setFont(OrgSystem.getFont()); // NOI18N

        jLabel3.setText("Reciept Number List");

        javax.swing.GroupLayout jPanel52Layout = new javax.swing.GroupLayout(jPanel52);
        jPanel52.setLayout(jPanel52Layout);
        jPanel52Layout.setHorizontalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel52Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel127)
                    .addComponent(jLabel128)
                    .addComponent(jLabel129)
                    .addComponent(jLabel130)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel52Layout.createSequentialGroup()
                        .addGroup(jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(orderNum, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                .addComponent(supplier1))
                            .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(receiver, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel52Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(recieptnum, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(send, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel52Layout.setVerticalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel52Layout.createSequentialGroup()
                .addGroup(jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel52Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel127)
                                .addComponent(orderNum))
                            .addGroup(jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(recieptnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel52Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel128)
                                    .addComponent(supplier1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel129)
                                .addGap(97, 97, 97)
                                .addGroup(jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel130)
                                    .addComponent(receiver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel52Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jPanel54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel52Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(send, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        jTabbedPane17.addTab("Main", jPanel52);

        maincardGRNjPanel53.setLayout(new java.awt.CardLayout());

        grntbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"O001", "softlogic sri lanka", "G001", "2013-07-30"},
                {"O002", "metropolitan center", "G002", "2013-08-02"},
                {"O003", "tech zone", "G003", "2013-08-07"},
                {"O004", "softlogic sri lanka", "G004", "2013-08-12"}
            },
            new String [] {
                "Order Number", "Supplier", "GRN No", "Sent Date"
            }
        ));
        jScrollPane20.setViewportView(grntbl);

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x32/Update.png"))); // NOI18N
        jButton17.setText("Update");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x32/Recycle Bin Full.png"))); // NOI18N
        jButton64.setText("Delete");

        javax.swing.GroupLayout GRNdetailsjPanel53Layout = new javax.swing.GroupLayout(GRNdetailsjPanel53);
        GRNdetailsjPanel53.setLayout(GRNdetailsjPanel53Layout);
        GRNdetailsjPanel53Layout.setHorizontalGroup(
            GRNdetailsjPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GRNdetailsjPanel53Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GRNdetailsjPanel53Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton17)
                .addGap(52, 52, 52)
                .addComponent(jButton64)
                .addGap(34, 34, 34))
        );
        GRNdetailsjPanel53Layout.setVerticalGroup(
            GRNdetailsjPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GRNdetailsjPanel53Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(GRNdetailsjPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton64)
                    .addComponent(jButton17))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        maincardGRNjPanel53.add(GRNdetailsjPanel53, "card2");

        jTextField97.setFont(OrgSystem.getFont()); // NOI18N

        jLabel133.setFont(OrgSystem.getFont()); // NOI18N
        jLabel133.setText("Order Number");

        jLabel134.setFont(OrgSystem.getFont()); // NOI18N
        jLabel134.setText("Supplier");

        jTextField98.setFont(OrgSystem.getFont()); // NOI18N

        jLabel136.setFont(OrgSystem.getFont()); // NOI18N
        jLabel136.setText("GRN No");

        jTextField99.setFont(OrgSystem.getFont()); // NOI18N

        jButton63.setFont(OrgSystem.getFont()); // NOI18N
        jButton63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Windows Card Space.png"))); // NOI18N
        jButton63.setText("Add");
        jButton63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton63ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updateGRNjPanel53Layout = new javax.swing.GroupLayout(updateGRNjPanel53);
        updateGRNjPanel53.setLayout(updateGRNjPanel53Layout);
        updateGRNjPanel53Layout.setHorizontalGroup(
            updateGRNjPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateGRNjPanel53Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(updateGRNjPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton63, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(updateGRNjPanel53Layout.createSequentialGroup()
                        .addGroup(updateGRNjPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel133)
                            .addComponent(jLabel136, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel134))
                        .addGap(39, 39, 39)
                        .addGroup(updateGRNjPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField99, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField97, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(jTextField98))
                        .addGap(219, 219, 219)))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        updateGRNjPanel53Layout.setVerticalGroup(
            updateGRNjPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateGRNjPanel53Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(updateGRNjPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel133)
                    .addComponent(jTextField97, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(updateGRNjPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel136)
                    .addComponent(jTextField99, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(updateGRNjPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel134)
                    .addComponent(jTextField98, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(jButton63)
                .addGap(151, 151, 151))
        );

        maincardGRNjPanel53.add(updateGRNjPanel53, "card3");

        jTabbedPane17.addTab("Line", maincardGRNjPanel53);

        javax.swing.GroupLayout jPanel58Layout = new javax.swing.GroupLayout(jPanel58);
        jPanel58.setLayout(jPanel58Layout);
        jPanel58Layout.setHorizontalGroup(
            jPanel58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane17)
        );
        jPanel58Layout.setVerticalGroup(
            jPanel58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane17)
        );

        jTabbedPane16.addTab("GRN Entry", new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/BitLocker.png")), jPanel58); // NOI18N

        javax.swing.GroupLayout jPanel55Layout = new javax.swing.GroupLayout(jPanel55);
        jPanel55.setLayout(jPanel55Layout);
        jPanel55Layout.setHorizontalGroup(
            jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane16)
        );
        jPanel55Layout.setVerticalGroup(
            jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 525, Short.MAX_VALUE)
        );

        jTabbedPane5.addTab("Payments", new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Folder Options.png")), jPanel55); // NOI18N

        jTabbedPane18.setFont(OrgSystem.getFont()); // NOI18N

        maincardconfirmationjPanel49.setLayout(new java.awt.CardLayout());

        jLabel123.setFont(OrgSystem.getFont()); // NOI18N
        jLabel123.setText("Invoice number");

        jLabel135.setFont(OrgSystem.getFont()); // NOI18N
        jLabel135.setText("Purchase date");

        jLabel137.setFont(OrgSystem.getFont()); // NOI18N
        jLabel137.setText("Quantity");

        jLabel139.setFont(OrgSystem.getFont()); // NOI18N
        jLabel139.setText("Supplier");

        invoiceNum.setFont(OrgSystem.getFont()); // NOI18N

        PurchaseDate.setFont(OrgSystem.getFont()); // NOI18N

        Quantity.setFont(OrgSystem.getFont()); // NOI18N

        Supplier.setFont(OrgSystem.getFont()); // NOI18N

        jButton69.setFont(OrgSystem.getFont()); // NOI18N
        jButton69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Windows Card Space.png"))); // NOI18N
        jButton69.setText("Add");
        jButton69.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton69ActionPerformed(evt);
            }
        });

        jLabel145.setFont(OrgSystem.getFont()); // NOI18N
        jLabel145.setText("Item");

        Item.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laptop", "Printers", "Mouse" }));

        javax.swing.GroupLayout addjPanel53Layout = new javax.swing.GroupLayout(addjPanel53);
        addjPanel53.setLayout(addjPanel53Layout);
        addjPanel53Layout.setHorizontalGroup(
            addjPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addjPanel53Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(addjPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel145, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel123, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel135, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel137, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel139, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(61, 61, 61)
                .addGroup(addjPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Supplier)
                    .addGroup(addjPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton69, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(addjPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(invoiceNum, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(PurchaseDate, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(Quantity, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(Item, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(361, Short.MAX_VALUE))
        );
        addjPanel53Layout.setVerticalGroup(
            addjPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addjPanel53Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(addjPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel123)
                    .addComponent(invoiceNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(addjPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel135)
                    .addComponent(PurchaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(addjPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel145)
                    .addComponent(Item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(addjPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel137))
                .addGap(38, 38, 38)
                .addGroup(addjPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel139))
                .addGap(83, 83, 83)
                .addComponent(jButton69)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        maincardconfirmationjPanel49.add(addjPanel53, "card3");

        jTabbedPane18.addTab("Add purchase", new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Color Management.png")), maincardconfirmationjPanel49); // NOI18N

        maincardpurchsesjPanel57.setLayout(new java.awt.CardLayout());

        jTable17.setFont(OrgSystem.getFont()); // NOI18N
        jTable17.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"I001", "2013-07-30", "Canon printer", "5", "kotte", "softlogic sri lanka"},
                {"I002", "2013-08-02", "HP PC", "20", "nugegoda", "tech zone"},
                {"I003", "2013-08-05", "HP mouse", "10", "galle", "metropolitan"},
                {"I004", "2013-08-12", "dell PC", "20", "kotte", "metropolitan"}
            },
            new String [] {
                "Invoice number", "Purchase date", "Item", "Quantity", "Branch", "Supplier"
            }
        ));
        jScrollPane21.setViewportView(jTable17);

        jButton71.setFont(OrgSystem.getFont()); // NOI18N
        jButton71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Update.png"))); // NOI18N
        jButton71.setText("Update");
        jButton71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton71ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout detailsjPanel49Layout = new javax.swing.GroupLayout(detailsjPanel49);
        detailsjPanel49.setLayout(detailsjPanel49Layout);
        detailsjPanel49Layout.setHorizontalGroup(
            detailsjPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsjPanel49Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane21, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailsjPanel49Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton71)
                .addGap(48, 48, 48))
        );
        detailsjPanel49Layout.setVerticalGroup(
            detailsjPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsjPanel49Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane21, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addGap(92, 92, 92)
                .addComponent(jButton71)
                .addGap(148, 148, 148))
        );

        maincardpurchsesjPanel57.add(detailsjPanel49, "card2");

        jLabel140.setFont(OrgSystem.getFont()); // NOI18N
        jLabel140.setText("Invoice number");

        jTextField104.setFont(OrgSystem.getFont()); // NOI18N

        jLabel141.setFont(OrgSystem.getFont()); // NOI18N
        jLabel141.setText("Purchase date");

        jTextField105.setFont(OrgSystem.getFont()); // NOI18N

        jLabel142.setFont(OrgSystem.getFont()); // NOI18N
        jLabel142.setText("Quantity");

        jTextField106.setFont(OrgSystem.getFont()); // NOI18N

        jLabel143.setFont(OrgSystem.getFont()); // NOI18N
        jLabel143.setText("Branch");

        jTextField107.setFont(OrgSystem.getFont()); // NOI18N

        jLabel144.setFont(OrgSystem.getFont()); // NOI18N
        jLabel144.setText("Supplier");

        jTextField108.setFont(OrgSystem.getFont()); // NOI18N

        jButton72.setFont(OrgSystem.getFont()); // NOI18N
        jButton72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Windows Card Space.png"))); // NOI18N
        jButton72.setText("Add");
        jButton72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton72ActionPerformed(evt);
            }
        });

        jButton73.setFont(OrgSystem.getFont()); // NOI18N
        jButton73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Recycle Bin Full.png"))); // NOI18N
        jButton73.setText("Close");
        jButton73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton73ActionPerformed(evt);
            }
        });

        jLabel146.setFont(OrgSystem.getFont()); // NOI18N
        jLabel146.setText("Item");

        jTextField110.setFont(OrgSystem.getFont()); // NOI18N

        javax.swing.GroupLayout updatejPanel53Layout = new javax.swing.GroupLayout(updatejPanel53);
        updatejPanel53.setLayout(updatejPanel53Layout);
        updatejPanel53Layout.setHorizontalGroup(
            updatejPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatejPanel53Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(updatejPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel144, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(updatejPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel140, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel141, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel142, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel143, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel146, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(61, 61, 61)
                .addGroup(updatejPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updatejPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField104, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addComponent(jTextField105, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addComponent(jTextField106, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addComponent(jTextField107, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addComponent(jTextField110, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                    .addComponent(jTextField108, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(361, Short.MAX_VALUE))
            .addGroup(updatejPanel53Layout.createSequentialGroup()
                .addGap(341, 341, 341)
                .addComponent(jButton72, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton73)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        updatejPanel53Layout.setVerticalGroup(
            updatejPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatejPanel53Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(updatejPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel140)
                    .addComponent(jTextField104, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(updatejPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel141)
                    .addComponent(jTextField105, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(updatejPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel146)
                    .addComponent(jTextField110, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(updatejPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel142)
                    .addComponent(jTextField106, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(updatejPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel143)
                    .addComponent(jTextField107, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(updatejPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel144)
                    .addComponent(jTextField108, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(updatejPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton72)
                    .addComponent(jButton73))
                .addGap(23, 23, 23))
        );

        maincardpurchsesjPanel57.add(updatejPanel53, "card3");

        jTabbedPane18.addTab("Purchase details", new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/Backup and Restore.png")), maincardpurchsesjPanel57); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane18)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane18)
        );

        jTabbedPane5.addTab("Purchases", new javax.swing.ImageIcon(getClass().getResource("/OrganizedIn/Res/Images/x16/AutoPlay.png")), jPanel10); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton69ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton69ActionPerformed
        // TODO add your handling code here:
        //addjPanel53.setVisible(false);
        //confirmjPanel49.setVisible(true);
        
        String invoicenum = invoiceNum.getText();
        String purchsedate = PurchaseDate.getText();
        String item = null;
        item = Item.getSelectedItem().toString();
        String quantity = Quantity.getText();
        String supplier = Supplier.getText();
        
        if(!invoicenum.equals(null) && !purchsedate.equals(null) && !item.equals(null)&& !quantity.equals(null) && !supplier.equals(null)){
            //boolean ds4 = hp.addPurchaseDetails(invoicenum,purchsedate,item,quantity,supplier);
            String st3 = "Successfully inserted..!!";
            JOptionPane.showMessageDialog(null, st3);

        }
        else{
            String st3 = "Please fill all the fields !!";
            JOptionPane.showMessageDialog(null, st3);
        }
        
        
        
        
    }//GEN-LAST:event_jButton69ActionPerformed

    private void jButton71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton71ActionPerformed
        // TODO add your handling code here:
        detailsjPanel49.setVisible(false);
        updatejPanel53.setVisible(true);
    }//GEN-LAST:event_jButton71ActionPerformed

    private void jButton72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton72ActionPerformed
        // TODO add your handling code here:
        updatejPanel53.setVisible(false);
        detailsjPanel49.setVisible(true);
    }//GEN-LAST:event_jButton72ActionPerformed

    private void jButton73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton73ActionPerformed
        // TODO add your handling code here:
        updatejPanel53.setVisible(false);
        detailsjPanel49.setVisible(true);
    }//GEN-LAST:event_jButton73ActionPerformed

    private void jButton63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton63ActionPerformed
        // TODO add your handling code here:
        updateGRNjPanel53.setVisible(false);
        GRNdetailsjPanel53.setVisible(true);
    }//GEN-LAST:event_jButton63ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        GRNdetailsjPanel53.setVisible(false);
        updateGRNjPanel53.setVisible(true);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton67ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton67ActionPerformed

    private void jButton60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton60ActionPerformed
        // TODO add your handling code here:
        String reciptNum = reciptnum.getText();
        int recptNumInt = Integer.parseInt(reciptNum);
        
        String totAmount = totamount.getText();
        Double totAmountDbl = Double.parseDouble(totAmount);
        
        String moneyType = null;
        moneyType = jComboBox1.getSelectedItem().toString();
        
        String date = date1.getText();
        
        String invNo = invoicenum.getSelectedItem().toString();
        int invNoInt = Integer.parseInt(invNo);

//        if(!reciptNum.equals(null) && !totAmount.equals(null) && !moneyType.equals(null)&& !date.equals(null) && !invNo.equals(null)){
//            boolean ds4 = hp.addPaymentDetails(recptNumInt, totAmountDbl,  moneyType, date, invNoInt);
//            
//            if(ds4==true){
//                String st3 = "Successfully inserted..!!";
//                JOptionPane.showMessageDialog(null, st3);
//            }
//            else{
//                 String st3 = "Operation failed..!!";
//                JOptionPane.showMessageDialog(null, st3);
//                
//            }
//            
//        }
//        else{
//            String st3 = "Please fill all the fields !!";
//            JOptionPane.showMessageDialog(null, st3);
//        }

    }//GEN-LAST:event_jButton60ActionPerformed

    private void jButton65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton65ActionPerformed
        // TODO add your handling code here:
        String ordernum = orderNum.getText();
        String supplier = supplier1.getText();
        String GRNdes = GRNDes.getText();
        String REciver = receiver.getText();
        String sender = send.getText();
        String recipt = recieptnum.getSelectedItem().toString();
        
//         if(!ordernum.equals(null) && !supplier.equals(null) && !GRNdes.equals(null)&& !REciver.equals(null) && !sender.equals(null) && !recipt.equals(null)){
////            boolean ds4 = hp.addGRNDetails(supplier,GRNdes,recipt,ordernum );
//            
//            if(ds4==true){
//                String st3 = "Successfully inserted..!!";
//                JOptionPane.showMessageDialog(null, st3);
//            }
//            else{
//                 String st3 = "Operation failed..!!";
//                JOptionPane.showMessageDialog(null, st3);
//                
//            }
//            
//        }
//        else{
//            String st3 = "Please fill all the fields !!";
//            JOptionPane.showMessageDialog(null, st3);
//        }
//        
        
        
    }//GEN-LAST:event_jButton65ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea GRNDes;
    private javax.swing.JPanel GRNdetailsjPanel53;
    private javax.swing.JComboBox Item;
    private javax.swing.JTextField PurchaseDate;
    private javax.swing.JTextField Quantity;
    private javax.swing.JTextField Supplier;
    private javax.swing.JPanel addjPanel53;
    private javax.swing.JTextField date1;
    private javax.swing.JPanel detailsjPanel49;
    private javax.swing.JTable grntbl;
    private javax.swing.JTextField invoiceNum;
    private javax.swing.JComboBox invoicenum;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JLabel jLabel146;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JTabbedPane jTabbedPane16;
    private javax.swing.JTabbedPane jTabbedPane17;
    private javax.swing.JTabbedPane jTabbedPane18;
    public javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTable jTable17;
    private javax.swing.JTextField jTextField104;
    private javax.swing.JTextField jTextField105;
    private javax.swing.JTextField jTextField106;
    private javax.swing.JTextField jTextField107;
    private javax.swing.JTextField jTextField108;
    private javax.swing.JTextField jTextField110;
    private javax.swing.JTextField jTextField97;
    private javax.swing.JTextField jTextField98;
    private javax.swing.JTextField jTextField99;
    private javax.swing.JPanel maincardGRNjPanel53;
    private javax.swing.JPanel maincardconfirmationjPanel49;
    private javax.swing.JPanel maincardpurchsesjPanel57;
    private javax.swing.JTextField orderNum;
    private javax.swing.JTextField receiver;
    private javax.swing.JComboBox recieptnum;
    private javax.swing.JTextField reciptnum;
    private javax.swing.JTextField send;
    private javax.swing.JTextField supplier1;
    private javax.swing.JTextField totamount;
    private javax.swing.JPanel updateGRNjPanel53;
    private javax.swing.JPanel updatejPanel53;
    // End of variables declaration//GEN-END:variables
}
